/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function agentEngineMemoryConfigToVertex(
  fromObject: types.AgentEngineMemoryConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (parentObject !== undefined && fromDisplayName != null) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  const fromDescription = common.getValueByPath(fromObject, ['description']);
  if (parentObject !== undefined && fromDescription != null) {
    common.setValueByPath(parentObject, ['description'], fromDescription);
  }

  const fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (parentObject !== undefined && fromTtl != null) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  const fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (parentObject !== undefined && fromExpireTime != null) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromTopics = common.getValueByPath(fromObject, ['topics']);
  if (parentObject !== undefined && fromTopics != null) {
    let transformedList = fromTopics;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['topics'], transformedList);
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMemoryId = common.getValueByPath(fromObject, ['memoryId']);
  if (parentObject !== undefined && fromMemoryId != null) {
    common.setValueByPath(parentObject, ['_query', 'memoryId'], fromMemoryId);
  }

  return toObject;
}

export function createAgentEngineMemoryRequestParametersToVertex(
  fromObject: types.CreateAgentEngineMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromFact = common.getValueByPath(fromObject, ['fact']);
  if (fromFact != null) {
    common.setValueByPath(toObject, ['fact'], fromFact);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    agentEngineMemoryConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function deleteAgentEngineMemoryRequestParametersToVertex(
  fromObject: types.DeleteAgentEngineMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function generateAgentEngineMemoriesConfigToVertex(
  fromObject: types.GenerateAgentEngineMemoriesConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisableConsolidation = common.getValueByPath(fromObject, [
    'disableConsolidation',
  ]);
  if (parentObject !== undefined && fromDisableConsolidation != null) {
    common.setValueByPath(
      parentObject,
      ['disableConsolidation'],
      fromDisableConsolidation,
    );
  }

  const fromRevisionLabels = common.getValueByPath(fromObject, [
    'revisionLabels',
  ]);
  if (parentObject !== undefined && fromRevisionLabels != null) {
    common.setValueByPath(parentObject, ['revisionLabels'], fromRevisionLabels);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMetadataMergeStrategy = common.getValueByPath(fromObject, [
    'metadataMergeStrategy',
  ]);
  if (parentObject !== undefined && fromMetadataMergeStrategy != null) {
    common.setValueByPath(
      parentObject,
      ['metadataMergeStrategy'],
      fromMetadataMergeStrategy,
    );
  }

  const fromAllowedTopics = common.getValueByPath(fromObject, [
    'allowedTopics',
  ]);
  if (parentObject !== undefined && fromAllowedTopics != null) {
    let transformedList = fromAllowedTopics;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['allowedTopics'], transformedList);
  }

  return toObject;
}

export function generateAgentEngineMemoriesRequestParametersToVertex(
  fromObject: types.GenerateAgentEngineMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromVertexSessionSource = common.getValueByPath(fromObject, [
    'vertexSessionSource',
  ]);
  if (fromVertexSessionSource != null) {
    common.setValueByPath(
      toObject,
      ['vertexSessionSource'],
      fromVertexSessionSource,
    );
  }

  const fromDirectContentsSource = common.getValueByPath(fromObject, [
    'directContentsSource',
  ]);
  if (fromDirectContentsSource != null) {
    common.setValueByPath(
      toObject,
      ['directContentsSource'],
      fromDirectContentsSource,
    );
  }

  const fromDirectMemoriesSource = common.getValueByPath(fromObject, [
    'directMemoriesSource',
  ]);
  if (fromDirectMemoriesSource != null) {
    common.setValueByPath(
      toObject,
      ['directMemoriesSource'],
      fromDirectMemoriesSource,
    );
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    generateAgentEngineMemoriesConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function getAgentEngineGenerateMemoriesOperationParametersToVertex(
  fromObject: types.GetAgentEngineGenerateMemoriesOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function getAgentEngineMemoryOperationParametersToVertex(
  fromObject: types.GetAgentEngineMemoryOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function getAgentEngineMemoryRequestParametersToVertex(
  fromObject: types.GetAgentEngineMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function ingestEventsConfigToVertex(
  fromObject: types.IngestEventsConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromForceFlush = common.getValueByPath(fromObject, ['forceFlush']);
  if (parentObject !== undefined && fromForceFlush != null) {
    common.setValueByPath(parentObject, ['forceFlush'], fromForceFlush);
  }

  return toObject;
}

export function ingestEventsRequestParametersToVertex(
  fromObject: types.IngestEventsRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromStreamId = common.getValueByPath(fromObject, ['streamId']);
  if (fromStreamId != null) {
    common.setValueByPath(toObject, ['streamId'], fromStreamId);
  }

  const fromDirectContentsSource = common.getValueByPath(fromObject, [
    'directContentsSource',
  ]);
  if (fromDirectContentsSource != null) {
    common.setValueByPath(
      toObject,
      ['directContentsSource'],
      fromDirectContentsSource,
    );
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromGenerationTriggerConfig = common.getValueByPath(fromObject, [
    'generationTriggerConfig',
  ]);
  if (fromGenerationTriggerConfig != null) {
    common.setValueByPath(
      toObject,
      ['generationTriggerConfig'],
      fromGenerationTriggerConfig,
    );
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    ingestEventsConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function listAgentEngineMemoryConfigToVertex(
  fromObject: types.ListAgentEngineMemoryConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (parentObject !== undefined && fromPageSize != null) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  const fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (parentObject !== undefined && fromPageToken != null) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['_query', 'filter'], fromFilter);
  }

  const fromOrderBy = common.getValueByPath(fromObject, ['orderBy']);
  if (parentObject !== undefined && fromOrderBy != null) {
    common.setValueByPath(parentObject, ['_query', 'orderBy'], fromOrderBy);
  }

  return toObject;
}

export function listAgentEngineMemoryRequestParametersToVertex(
  fromObject: types.ListAgentEngineMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    listAgentEngineMemoryConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function purgeAgentEngineMemoriesRequestParametersToVertex(
  fromObject: types.PurgeAgentEngineMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (fromFilter != null) {
    common.setValueByPath(toObject, ['filter'], fromFilter);
  }

  const fromFilterGroups = common.getValueByPath(fromObject, ['filterGroups']);
  if (fromFilterGroups != null) {
    let transformedList = fromFilterGroups;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(toObject, ['filterGroups'], transformedList);
  }

  const fromForce = common.getValueByPath(fromObject, ['force']);
  if (fromForce != null) {
    common.setValueByPath(toObject, ['force'], fromForce);
  }

  return toObject;
}

export function retrieveAgentEngineMemoriesConfigToVertex(
  fromObject: types.RetrieveAgentEngineMemoriesConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['filter'], fromFilter);
  }

  const fromFilterGroups = common.getValueByPath(fromObject, ['filterGroups']);
  if (parentObject !== undefined && fromFilterGroups != null) {
    let transformedList = fromFilterGroups;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['filterGroups'], transformedList);
  }

  const fromMemoryTypes = common.getValueByPath(fromObject, ['memoryTypes']);
  if (parentObject !== undefined && fromMemoryTypes != null) {
    common.setValueByPath(parentObject, ['memoryTypes'], fromMemoryTypes);
  }

  return toObject;
}

export function retrieveAgentEngineMemoriesRequestParametersToVertex(
  fromObject: types.RetrieveAgentEngineMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromSimilaritySearchParams = common.getValueByPath(fromObject, [
    'similaritySearchParams',
  ]);
  if (fromSimilaritySearchParams != null) {
    common.setValueByPath(
      toObject,
      ['similaritySearchParams'],
      fromSimilaritySearchParams,
    );
  }

  const fromSimpleRetrievalParams = common.getValueByPath(fromObject, [
    'simpleRetrievalParams',
  ]);
  if (fromSimpleRetrievalParams != null) {
    common.setValueByPath(
      toObject,
      ['simpleRetrievalParams'],
      fromSimpleRetrievalParams,
    );
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    retrieveAgentEngineMemoriesConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function retrieveMemoryProfilesRequestParametersToVertex(
  fromObject: types.RetrieveMemoryProfilesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  return toObject;
}

export function rollbackAgentEngineMemoryRequestParametersToVertex(
  fromObject: types.RollbackAgentEngineMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromTargetRevisionId = common.getValueByPath(fromObject, [
    'targetRevisionId',
  ]);
  if (fromTargetRevisionId != null) {
    common.setValueByPath(toObject, ['targetRevisionId'], fromTargetRevisionId);
  }

  return toObject;
}

export function updateAgentEngineMemoryConfigToVertex(
  fromObject: types.UpdateAgentEngineMemoryConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (parentObject !== undefined && fromDisplayName != null) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  const fromDescription = common.getValueByPath(fromObject, ['description']);
  if (parentObject !== undefined && fromDescription != null) {
    common.setValueByPath(parentObject, ['description'], fromDescription);
  }

  const fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (parentObject !== undefined && fromTtl != null) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  const fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (parentObject !== undefined && fromExpireTime != null) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromTopics = common.getValueByPath(fromObject, ['topics']);
  if (parentObject !== undefined && fromTopics != null) {
    let transformedList = fromTopics;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['topics'], transformedList);
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMemoryId = common.getValueByPath(fromObject, ['memoryId']);
  if (parentObject !== undefined && fromMemoryId != null) {
    common.setValueByPath(parentObject, ['_query', 'memoryId'], fromMemoryId);
  }

  const fromUpdateMask = common.getValueByPath(fromObject, ['updateMask']);
  if (parentObject !== undefined && fromUpdateMask != null) {
    common.setValueByPath(
      parentObject,
      ['_query', 'updateMask'],
      fromUpdateMask,
    );
  }

  return toObject;
}

export function updateAgentEngineMemoryRequestParametersToVertex(
  fromObject: types.UpdateAgentEngineMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromFact = common.getValueByPath(fromObject, ['fact']);
  if (fromFact != null) {
    common.setValueByPath(toObject, ['fact'], fromFact);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    updateAgentEngineMemoryConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}
