/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function createMemoryRequestParametersToVertex(
  fromObject: types.CreateMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromFact = common.getValueByPath(fromObject, ['fact']);
  if (fromFact != null) {
    common.setValueByPath(toObject, ['fact'], fromFact);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    memoryConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function deleteMemoryRequestParametersToVertex(
  fromObject: types.DeleteMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function generateMemoriesConfigToVertex(
  fromObject: types.GenerateMemoriesConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisableConsolidation = common.getValueByPath(fromObject, [
    'disableConsolidation',
  ]);
  if (parentObject !== undefined && fromDisableConsolidation != null) {
    common.setValueByPath(
      parentObject,
      ['disableConsolidation'],
      fromDisableConsolidation,
    );
  }

  const fromRevisionLabels = common.getValueByPath(fromObject, [
    'revisionLabels',
  ]);
  if (parentObject !== undefined && fromRevisionLabels != null) {
    common.setValueByPath(parentObject, ['revisionLabels'], fromRevisionLabels);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMetadataMergeStrategy = common.getValueByPath(fromObject, [
    'metadataMergeStrategy',
  ]);
  if (parentObject !== undefined && fromMetadataMergeStrategy != null) {
    common.setValueByPath(
      parentObject,
      ['metadataMergeStrategy'],
      fromMetadataMergeStrategy,
    );
  }

  const fromAllowedTopics = common.getValueByPath(fromObject, [
    'allowedTopics',
  ]);
  if (parentObject !== undefined && fromAllowedTopics != null) {
    let transformedList = fromAllowedTopics;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['allowedTopics'], transformedList);
  }

  return toObject;
}

export function generateMemoriesRequestParametersToVertex(
  fromObject: types.GenerateMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromVertexSessionSource = common.getValueByPath(fromObject, [
    'vertexSessionSource',
  ]);
  if (fromVertexSessionSource != null) {
    common.setValueByPath(
      toObject,
      ['vertexSessionSource'],
      fromVertexSessionSource,
    );
  }

  const fromDirectContentsSource = common.getValueByPath(fromObject, [
    'directContentsSource',
  ]);
  if (fromDirectContentsSource != null) {
    common.setValueByPath(
      toObject,
      ['directContentsSource'],
      fromDirectContentsSource,
    );
  }

  const fromDirectMemoriesSource = common.getValueByPath(fromObject, [
    'directMemoriesSource',
  ]);
  if (fromDirectMemoriesSource != null) {
    common.setValueByPath(
      toObject,
      ['directMemoriesSource'],
      fromDirectMemoriesSource,
    );
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    generateMemoriesConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function getGenerateMemoriesOperationParametersToVertex(
  fromObject: types.GetGenerateMemoriesOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function getMemoryOperationParametersToVertex(
  fromObject: types.GetMemoryOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function getMemoryRequestParametersToVertex(
  fromObject: types.GetMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function listMemoriesConfigToVertex(
  fromObject: types.ListMemoriesConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (parentObject !== undefined && fromPageSize != null) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  const fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (parentObject !== undefined && fromPageToken != null) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['_query', 'filter'], fromFilter);
  }

  const fromOrderBy = common.getValueByPath(fromObject, ['orderBy']);
  if (parentObject !== undefined && fromOrderBy != null) {
    common.setValueByPath(parentObject, ['_query', 'orderBy'], fromOrderBy);
  }

  return toObject;
}

export function listMemoriesRequestParametersToVertex(
  fromObject: types.ListMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    listMemoriesConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function memoryConfigToVertex(
  fromObject: types.MemoryConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (parentObject !== undefined && fromDisplayName != null) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  const fromDescription = common.getValueByPath(fromObject, ['description']);
  if (parentObject !== undefined && fromDescription != null) {
    common.setValueByPath(parentObject, ['description'], fromDescription);
  }

  const fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (parentObject !== undefined && fromTtl != null) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  const fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (parentObject !== undefined && fromExpireTime != null) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromTopics = common.getValueByPath(fromObject, ['topics']);
  if (parentObject !== undefined && fromTopics != null) {
    let transformedList = fromTopics;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['topics'], transformedList);
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMemoryId = common.getValueByPath(fromObject, ['memoryId']);
  if (parentObject !== undefined && fromMemoryId != null) {
    common.setValueByPath(parentObject, ['_query', 'memoryId'], fromMemoryId);
  }

  return toObject;
}

export function purgeMemoriesRequestParametersToVertex(
  fromObject: types.PurgeMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (fromFilter != null) {
    common.setValueByPath(toObject, ['filter'], fromFilter);
  }

  const fromFilterGroups = common.getValueByPath(fromObject, ['filterGroups']);
  if (fromFilterGroups != null) {
    let transformedList = fromFilterGroups;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(toObject, ['filterGroups'], transformedList);
  }

  const fromForce = common.getValueByPath(fromObject, ['force']);
  if (fromForce != null) {
    common.setValueByPath(toObject, ['force'], fromForce);
  }

  return toObject;
}

export function retrieveMemoriesConfigToVertex(
  fromObject: types.RetrieveMemoriesConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['filter'], fromFilter);
  }

  const fromFilterGroups = common.getValueByPath(fromObject, ['filterGroups']);
  if (parentObject !== undefined && fromFilterGroups != null) {
    let transformedList = fromFilterGroups;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['filterGroups'], transformedList);
  }

  const fromMemoryTypes = common.getValueByPath(fromObject, ['memoryTypes']);
  if (parentObject !== undefined && fromMemoryTypes != null) {
    common.setValueByPath(parentObject, ['memoryTypes'], fromMemoryTypes);
  }

  return toObject;
}

export function retrieveMemoriesRequestParametersToVertex(
  fromObject: types.RetrieveMemoriesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromSimilaritySearchParams = common.getValueByPath(fromObject, [
    'similaritySearchParams',
  ]);
  if (fromSimilaritySearchParams != null) {
    common.setValueByPath(
      toObject,
      ['similaritySearchParams'],
      fromSimilaritySearchParams,
    );
  }

  const fromSimpleRetrievalParams = common.getValueByPath(fromObject, [
    'simpleRetrievalParams',
  ]);
  if (fromSimpleRetrievalParams != null) {
    common.setValueByPath(
      toObject,
      ['simpleRetrievalParams'],
      fromSimpleRetrievalParams,
    );
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    retrieveMemoriesConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function retrieveMemoryProfilesRequestParametersToVertex(
  fromObject: types.RetrieveMemoryProfilesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  return toObject;
}

export function rollbackMemoryRequestParametersToVertex(
  fromObject: types.RollbackMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromTargetRevisionId = common.getValueByPath(fromObject, [
    'targetRevisionId',
  ]);
  if (fromTargetRevisionId != null) {
    common.setValueByPath(toObject, ['targetRevisionId'], fromTargetRevisionId);
  }

  return toObject;
}

export function updateMemoryConfigToVertex(
  fromObject: types.UpdateMemoryConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (parentObject !== undefined && fromDisplayName != null) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  const fromDescription = common.getValueByPath(fromObject, ['description']);
  if (parentObject !== undefined && fromDescription != null) {
    common.setValueByPath(parentObject, ['description'], fromDescription);
  }

  const fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (parentObject !== undefined && fromTtl != null) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  const fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (parentObject !== undefined && fromExpireTime != null) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromTopics = common.getValueByPath(fromObject, ['topics']);
  if (parentObject !== undefined && fromTopics != null) {
    let transformedList = fromTopics;
    if (Array.isArray(transformedList)) {
      transformedList = transformedList.map((item) => {
        return item;
      });
    }
    common.setValueByPath(parentObject, ['topics'], transformedList);
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMemoryId = common.getValueByPath(fromObject, ['memoryId']);
  if (parentObject !== undefined && fromMemoryId != null) {
    common.setValueByPath(parentObject, ['_query', 'memoryId'], fromMemoryId);
  }

  const fromUpdateMask = common.getValueByPath(fromObject, ['updateMask']);
  if (parentObject !== undefined && fromUpdateMask != null) {
    common.setValueByPath(
      parentObject,
      ['_query', 'updateMask'],
      fromUpdateMask,
    );
  }

  return toObject;
}

export function updateMemoryRequestParametersToVertex(
  fromObject: types.UpdateMemoryRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromFact = common.getValueByPath(fromObject, ['fact']);
  if (fromFact != null) {
    common.setValueByPath(toObject, ['fact'], fromFact);
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    updateMemoryConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}
