/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function createMemoryBankRequestParametersToVertex(): Record<
  string,
  unknown
> {
  const toObject: Record<string, unknown> = {};

  return toObject;
}

export function deleteMemoryBankRequestParametersToVertex(
  fromObject: types.DeleteMemoryBankRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromForce = common.getValueByPath(fromObject, ['force']);
  if (fromForce != null) {
    common.setValueByPath(toObject, ['force'], fromForce);
  }

  return toObject;
}

export function getMemoryBankOperationParametersToVertex(
  fromObject: types.GetMemoryBankOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function ingestEventsConfigToVertex(
  fromObject: types.IngestEventsConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromForceFlush = common.getValueByPath(fromObject, ['forceFlush']);
  if (parentObject !== undefined && fromForceFlush != null) {
    common.setValueByPath(parentObject, ['forceFlush'], fromForceFlush);
  }

  const fromRevisionLabels = common.getValueByPath(fromObject, [
    'revisionLabels',
  ]);
  if (parentObject !== undefined && fromRevisionLabels != null) {
    common.setValueByPath(parentObject, ['revisionLabels'], fromRevisionLabels);
  }

  const fromRevisionExpireTime = common.getValueByPath(fromObject, [
    'revisionExpireTime',
  ]);
  if (parentObject !== undefined && fromRevisionExpireTime != null) {
    common.setValueByPath(
      parentObject,
      ['revisionExpireTime'],
      fromRevisionExpireTime,
    );
  }

  const fromRevisionTtl = common.getValueByPath(fromObject, ['revisionTtl']);
  if (parentObject !== undefined && fromRevisionTtl != null) {
    common.setValueByPath(parentObject, ['revisionTtl'], fromRevisionTtl);
  }

  const fromDisableMemoryRevisions = common.getValueByPath(fromObject, [
    'disableMemoryRevisions',
  ]);
  if (parentObject !== undefined && fromDisableMemoryRevisions != null) {
    common.setValueByPath(
      parentObject,
      ['disableMemoryRevisions'],
      fromDisableMemoryRevisions,
    );
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (parentObject !== undefined && fromMetadata != null) {
    common.setValueByPath(parentObject, ['metadata'], fromMetadata);
  }

  const fromMetadataMergeStrategy = common.getValueByPath(fromObject, [
    'metadataMergeStrategy',
  ]);
  if (parentObject !== undefined && fromMetadataMergeStrategy != null) {
    common.setValueByPath(
      parentObject,
      ['metadataMergeStrategy'],
      fromMetadataMergeStrategy,
    );
  }

  return toObject;
}

export function ingestEventsRequestParametersToVertex(
  fromObject: types.IngestEventsRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromStreamId = common.getValueByPath(fromObject, ['streamId']);
  if (fromStreamId != null) {
    common.setValueByPath(toObject, ['streamId'], fromStreamId);
  }

  const fromDirectContentsSource = common.getValueByPath(fromObject, [
    'directContentsSource',
  ]);
  if (fromDirectContentsSource != null) {
    common.setValueByPath(
      toObject,
      ['directContentsSource'],
      fromDirectContentsSource,
    );
  }

  const fromScope = common.getValueByPath(fromObject, ['scope']);
  if (fromScope != null) {
    common.setValueByPath(toObject, ['scope'], fromScope);
  }

  const fromGenerationTriggerConfig = common.getValueByPath(fromObject, [
    'generationTriggerConfig',
  ]);
  if (fromGenerationTriggerConfig != null) {
    common.setValueByPath(
      toObject,
      ['generationTriggerConfig'],
      fromGenerationTriggerConfig,
    );
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    ingestEventsConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}
