/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function createDatasetParametersToVertex(
  fromObject: types.CreateDatasetParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['name'], fromName);
  }

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName != null) {
    common.setValueByPath(toObject, ['displayName'], fromDisplayName);
  }

  const fromMetadataSchemaUri = common.getValueByPath(fromObject, [
    'metadataSchemaUri',
  ]);
  if (fromMetadataSchemaUri != null) {
    common.setValueByPath(
      toObject,
      ['metadataSchemaUri'],
      fromMetadataSchemaUri,
    );
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (fromMetadata != null) {
    common.setValueByPath(toObject, ['metadata'], fromMetadata);
  }

  const fromDescription = common.getValueByPath(fromObject, ['description']);
  if (fromDescription != null) {
    common.setValueByPath(toObject, ['description'], fromDescription);
  }

  const fromEncryptionSpec = common.getValueByPath(fromObject, [
    'encryptionSpec',
  ]);
  if (fromEncryptionSpec != null) {
    common.setValueByPath(toObject, ['encryptionSpec'], fromEncryptionSpec);
  }

  const fromModelReference = common.getValueByPath(fromObject, [
    'modelReference',
  ]);
  if (fromModelReference != null) {
    common.setValueByPath(toObject, ['modelReference'], fromModelReference);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function createDatasetVersionParametersToVertex(
  fromObject: types.CreateDatasetVersionParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDatasetName = common.getValueByPath(fromObject, ['datasetName']);
  if (fromDatasetName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromDatasetName);
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (fromMetadata != null) {
    common.setValueByPath(toObject, ['metadata'], fromMetadata);
  }

  const fromModelReference = common.getValueByPath(fromObject, [
    'modelReference',
  ]);
  if (fromModelReference != null) {
    common.setValueByPath(toObject, ['modelReference'], fromModelReference);
  }

  const fromParent = common.getValueByPath(fromObject, ['parent']);
  if (fromParent != null) {
    common.setValueByPath(toObject, ['parent'], fromParent);
  }

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName != null) {
    common.setValueByPath(toObject, ['displayName'], fromDisplayName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function deleteDatasetRequestParametersToVertex(
  fromObject: types.DeleteDatasetRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPromptId = common.getValueByPath(fromObject, ['promptId']);
  if (fromPromptId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromPromptId);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function deletePromptVersionRequestParametersToVertex(
  fromObject: types.DeletePromptVersionRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPromptId = common.getValueByPath(fromObject, ['promptId']);
  if (fromPromptId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromPromptId);
  }

  const fromVersionId = common.getValueByPath(fromObject, ['versionId']);
  if (fromVersionId != null) {
    common.setValueByPath(toObject, ['_url', 'version_id'], fromVersionId);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function getDatasetOperationParametersToVertex(
  fromObject: types.GetDatasetOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDatasetId = common.getValueByPath(fromObject, ['datasetId']);
  if (fromDatasetId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromDatasetId);
  }

  const fromOperationId = common.getValueByPath(fromObject, ['operationId']);
  if (fromOperationId != null) {
    common.setValueByPath(toObject, ['_url', 'operation_id'], fromOperationId);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function getDatasetParametersToVertex(
  fromObject: types.GetDatasetParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function getDatasetVersionParametersToVertex(
  fromObject: types.GetDatasetVersionParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDatasetId = common.getValueByPath(fromObject, ['datasetId']);
  if (fromDatasetId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromDatasetId);
  }

  const fromDatasetVersionId = common.getValueByPath(fromObject, [
    'datasetVersionId',
  ]);
  if (fromDatasetVersionId != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'dataset_version_id'],
      fromDatasetVersionId,
    );
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function listDatasetVersionsRequestParametersToVertex(
  fromObject: types.ListDatasetVersionsRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromReadMask = common.getValueByPath(fromObject, ['readMask']);
  if (fromReadMask != null) {
    common.setValueByPath(toObject, ['_url', 'read_mask'], fromReadMask);
  }

  const fromDatasetId = common.getValueByPath(fromObject, ['datasetId']);
  if (fromDatasetId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromDatasetId);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(
      toObject,
      ['config'],
      listPromptsConfigToVertex(fromConfig, toObject),
    );
  }

  return toObject;
}

export function listDatasetsRequestParametersToVertex(
  fromObject: types.ListDatasetsRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(
      toObject,
      ['config'],
      listPromptsConfigToVertex(fromConfig, toObject),
    );
  }

  return toObject;
}

export function listPromptsConfigToVertex(
  fromObject: types.ListPromptsConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (parentObject !== undefined && fromPageSize != null) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  const fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (parentObject !== undefined && fromPageToken != null) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['_query', 'filter'], fromFilter);
  }

  return toObject;
}

export function restoreVersionRequestParametersToVertex(
  fromObject: types.RestoreVersionRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDatasetId = common.getValueByPath(fromObject, ['datasetId']);
  if (fromDatasetId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromDatasetId);
  }

  const fromVersionId = common.getValueByPath(fromObject, ['versionId']);
  if (fromVersionId != null) {
    common.setValueByPath(toObject, ['_url', 'version_id'], fromVersionId);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

export function updateDatasetParametersToVertex(
  fromObject: types.UpdateDatasetParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['name'], fromName);
  }

  const fromDatasetId = common.getValueByPath(fromObject, ['datasetId']);
  if (fromDatasetId != null) {
    common.setValueByPath(toObject, ['_url', 'dataset_id'], fromDatasetId);
  }

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName != null) {
    common.setValueByPath(toObject, ['displayName'], fromDisplayName);
  }

  const fromMetadata = common.getValueByPath(fromObject, ['metadata']);
  if (fromMetadata != null) {
    common.setValueByPath(toObject, ['metadata'], fromMetadata);
  }

  const fromDescription = common.getValueByPath(fromObject, ['description']);
  if (fromDescription != null) {
    common.setValueByPath(toObject, ['description'], fromDescription);
  }

  const fromEncryptionSpec = common.getValueByPath(fromObject, [
    'encryptionSpec',
  ]);
  if (fromEncryptionSpec != null) {
    common.setValueByPath(toObject, ['encryptionSpec'], fromEncryptionSpec);
  }

  const fromModelReference = common.getValueByPath(fromObject, [
    'modelReference',
  ]);
  if (fromModelReference != null) {
    common.setValueByPath(toObject, ['modelReference'], fromModelReference);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}
