/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function createSandboxEnvironmentTemplateConfigToVertex(
  fromObject: types.CreateSandboxEnvironmentTemplateConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromCustomContainerEnvironment = common.getValueByPath(fromObject, [
    'customContainerEnvironment',
  ]);
  if (parentObject !== undefined && fromCustomContainerEnvironment != null) {
    common.setValueByPath(
      parentObject,
      ['customContainerEnvironment'],
      fromCustomContainerEnvironment,
    );
  }

  const fromDefaultContainerEnvironment = common.getValueByPath(fromObject, [
    'defaultContainerEnvironment',
  ]);
  if (parentObject !== undefined && fromDefaultContainerEnvironment != null) {
    common.setValueByPath(
      parentObject,
      ['defaultContainerEnvironment'],
      fromDefaultContainerEnvironment,
    );
  }

  const fromEgressControlConfig = common.getValueByPath(fromObject, [
    'egressControlConfig',
  ]);
  if (parentObject !== undefined && fromEgressControlConfig != null) {
    common.setValueByPath(
      parentObject,
      ['egressControlConfig'],
      fromEgressControlConfig,
    );
  }

  const fromIngressControlConfig = common.getValueByPath(fromObject, [
    'ingressControlConfig',
  ]);
  if (parentObject !== undefined && fromIngressControlConfig != null) {
    common.setValueByPath(
      parentObject,
      ['ingressControlConfig'],
      fromIngressControlConfig,
    );
  }

  return toObject;
}

export function createSandboxEnvironmentTemplateRequestParametersToVertex(
  fromObject: types.CreateSandboxEnvironmentTemplateRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName != null) {
    common.setValueByPath(toObject, ['displayName'], fromDisplayName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    createSandboxEnvironmentTemplateConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function deleteSandboxEnvironmentTemplateRequestParametersToVertex(
  fromObject: types.DeleteSandboxEnvironmentTemplateRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function getSandboxEnvironmentTemplateOperationParametersToVertex(
  fromObject: types.GetSandboxEnvironmentTemplateOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function getSandboxEnvironmentTemplateRequestParametersToVertex(
  fromObject: types.GetSandboxEnvironmentTemplateRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function listSandboxEnvironmentTemplatesConfigToVertex(
  fromObject: types.ListSandboxEnvironmentTemplatesConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (parentObject !== undefined && fromPageSize != null) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  const fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (parentObject !== undefined && fromPageToken != null) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['_query', 'filter'], fromFilter);
  }

  return toObject;
}

export function listSandboxEnvironmentTemplatesRequestParametersToVertex(
  fromObject: types.ListSandboxEnvironmentTemplatesRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    listSandboxEnvironmentTemplatesConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}
