/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function createAgentEngineSandboxSnapshotConfigToVertex(
  fromObject: types.CreateAgentEngineSandboxSnapshotConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (parentObject !== undefined && fromDisplayName != null) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  const fromOwner = common.getValueByPath(fromObject, ['owner']);
  if (parentObject !== undefined && fromOwner != null) {
    common.setValueByPath(parentObject, ['owner'], fromOwner);
  }

  const fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (parentObject !== undefined && fromTtl != null) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  return toObject;
}

export function createSandboxEnvironmentSnapshotRequestParametersToVertex(
  fromObject: types.CreateSandboxEnvironmentSnapshotRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromSourceSandboxEnvironmentName = common.getValueByPath(fromObject, [
    'sourceSandboxEnvironmentName',
  ]);
  if (fromSourceSandboxEnvironmentName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      fromSourceSandboxEnvironmentName,
    );
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    createAgentEngineSandboxSnapshotConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function deleteSandboxEnvironmentSnapshotRequestParametersToVertex(
  fromObject: types.DeleteSandboxEnvironmentSnapshotRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function getAgentEngineSandboxSnapshotOperationParametersToVertex(
  fromObject: types.GetAgentEngineSandboxSnapshotOperationParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromOperationName = common.getValueByPath(fromObject, [
    'operationName',
  ]);
  if (fromOperationName != null) {
    common.setValueByPath(
      toObject,
      ['_url', 'operationName'],
      fromOperationName,
    );
  }

  return toObject;
}

export function getSandboxEnvironmentSnapshotRequestParametersToVertex(
  fromObject: types.GetSandboxEnvironmentSnapshotRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  return toObject;
}

export function listSandboxEnvironmentSnapshotsConfigToVertex(
  fromObject: types.ListSandboxEnvironmentSnapshotsConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (parentObject !== undefined && fromPageSize != null) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  const fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (parentObject !== undefined && fromPageToken != null) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['_query', 'filter'], fromFilter);
  }

  return toObject;
}

export function listSandboxEnvironmentSnapshotsRequestParametersToVertex(
  fromObject: types.ListSandboxEnvironmentSnapshotsRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    listSandboxEnvironmentSnapshotsConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}
