/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import * as types from '../types.js';

export function appendAgentEngineSessionEventConfigToVertex(
  fromObject: types.AppendAgentEngineSessionEventConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromContent = common.getValueByPath(fromObject, ['content']);
  if (parentObject !== undefined && fromContent != null) {
    common.setValueByPath(parentObject, ['content'], fromContent);
  }

  const fromActions = common.getValueByPath(fromObject, ['actions']);
  if (parentObject !== undefined && fromActions != null) {
    common.setValueByPath(parentObject, ['actions'], fromActions);
  }

  const fromErrorCode = common.getValueByPath(fromObject, ['errorCode']);
  if (parentObject !== undefined && fromErrorCode != null) {
    common.setValueByPath(parentObject, ['errorCode'], fromErrorCode);
  }

  const fromErrorMessage = common.getValueByPath(fromObject, ['errorMessage']);
  if (parentObject !== undefined && fromErrorMessage != null) {
    common.setValueByPath(parentObject, ['errorMessage'], fromErrorMessage);
  }

  const fromEventMetadata = common.getValueByPath(fromObject, [
    'eventMetadata',
  ]);
  if (parentObject !== undefined && fromEventMetadata != null) {
    common.setValueByPath(parentObject, ['eventMetadata'], fromEventMetadata);
  }

  const fromRawEvent = common.getValueByPath(fromObject, ['rawEvent']);
  if (parentObject !== undefined && fromRawEvent != null) {
    common.setValueByPath(parentObject, ['rawEvent'], fromRawEvent);
  }

  return toObject;
}

export function appendAgentEngineSessionEventRequestParametersToVertex(
  fromObject: types.AppendAgentEngineSessionEventRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromAuthor = common.getValueByPath(fromObject, ['author']);
  if (fromAuthor != null) {
    common.setValueByPath(toObject, ['author'], fromAuthor);
  }

  const fromInvocationId = common.getValueByPath(fromObject, ['invocationId']);
  if (fromInvocationId != null) {
    common.setValueByPath(toObject, ['invocationId'], fromInvocationId);
  }

  const fromTimestamp = common.getValueByPath(fromObject, ['timestamp']);
  if (fromTimestamp != null) {
    common.setValueByPath(toObject, ['timestamp'], fromTimestamp);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    appendAgentEngineSessionEventConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}

export function listAgentEngineSessionEventsConfigToVertex(
  fromObject: types.ListAgentEngineSessionEventsConfig,
  parentObject: Record<string, unknown>,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (parentObject !== undefined && fromPageSize != null) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  const fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (parentObject !== undefined && fromPageToken != null) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  const fromFilter = common.getValueByPath(fromObject, ['filter']);
  if (parentObject !== undefined && fromFilter != null) {
    common.setValueByPath(parentObject, ['_query', 'filter'], fromFilter);
  }

  return toObject;
}

export function listAgentEngineSessionEventsRequestParametersToVertex(
  fromObject: types.ListAgentEngineSessionEventsRequestParameters,
): Record<string, unknown> {
  const toObject: Record<string, unknown> = {};

  const fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName != null) {
    common.setValueByPath(toObject, ['_url', 'name'], fromName);
  }

  const fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig != null) {
    listAgentEngineSessionEventsConfigToVertex(fromConfig, toObject);
  }

  return toObject;
}
