/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import {ApiClient} from 'google3/third_party/javascript/google_genai/src/_api_client.js';
import * as common from 'google3/third_party/javascript/google_genai/src/_common.js';
import {BaseModule} from 'google3/third_party/javascript/google_genai/src/_common.js';
import {NodeAuth} from 'google3/third_party/javascript/google_genai/src/g3_node/_g3_node_auth';
import {NodeUploader} from 'google3/third_party/javascript/google_genai/src/g3_node/_g3_node_uploader';
import {NodeDownloader} from 'google3/third_party/javascript/google_genai/src/node/_node_downloader';
import {
  PagedItem,
  Pager,
} from 'google3/third_party/javascript/google_genai/src/pagers.js';
import * as genaiTypes from 'google3/third_party/javascript/google_genai/src/types';
import * as converters from 'google3/third_party/javascript/node_modules/vertexai/src/genai/converters/_agentengines_converters.js';
import * as types from 'google3/third_party/javascript/node_modules/vertexai/src/genai/types.js';

export class AgentEngines extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  private async createInternal(
    params: types.CreateAgentEngineRequestParameters,
  ): Promise<types.AgentEngineOperation> {
    let response: Promise<types.AgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        'reasoningEngines',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async deleteInternal(
    params: types.DeleteAgentEngineRequestParameters,
  ): Promise<types.DeleteAgentEngineOperation> {
    let response: Promise<types.DeleteAgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteAgentEngineOperation>;

      return response.then((resp) => {
        return resp as types.DeleteAgentEngineOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async getInternal(
    params: types.GetAgentEngineRequestParameters,
  ): Promise<types.ReasoningEngine> {
    let response: Promise<types.ReasoningEngine>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ReasoningEngine>;

      return response.then((resp) => {
        return resp as types.ReasoningEngine;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async listInternal(
    params: types.ListAgentEngineRequestParameters,
  ): Promise<types.ListReasoningEnginesResponse> {
    let response: Promise<types.ListReasoningEnginesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.listAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        'reasoningEngines',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListReasoningEnginesResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListReasoningEnginesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async getAgentOperationInternal(
    params: types.GetAgentEngineOperationParameters,
  ): Promise<types.AgentEngineOperation> {
    let response: Promise<types.AgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getAgentEngineOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async queryInternal(
    params: types.QueryAgentEngineRequestParameters,
  ): Promise<types.QueryReasoningEngineResponse> {
    let response: Promise<types.QueryReasoningEngineResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.queryAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}:query',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.QueryReasoningEngineResponse>;

      return response.then((resp) => {
        const typedResp = new types.QueryReasoningEngineResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async updateInternal(
    params: types.UpdateAgentEngineRequestParameters,
  ): Promise<types.AgentEngineOperation> {
    let response: Promise<types.AgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.updateAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'PATCH',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }
}
