/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import {ApiClient} from 'google3/third_party/javascript/google_genai/src/_api_client.js';
import * as common from 'google3/third_party/javascript/google_genai/src/_common.js';
import {BaseModule} from 'google3/third_party/javascript/google_genai/src/_common.js';
import {NodeAuth} from 'google3/third_party/javascript/google_genai/src/g3_node/_g3_node_auth';
import {NodeUploader} from 'google3/third_party/javascript/google_genai/src/g3_node/_g3_node_uploader';
import {NodeDownloader} from 'google3/third_party/javascript/google_genai/src/node/_node_downloader';
import {
  PagedItem,
  Pager,
} from 'google3/third_party/javascript/google_genai/src/pagers.js';
import * as genaiTypes from 'google3/third_party/javascript/google_genai/src/types';
import * as converters from 'google3/third_party/javascript/node_modules/vertexai/src/genai/converters/_sessions_converters.js';
import * as types from 'google3/third_party/javascript/node_modules/vertexai/src/genai/types.js';

export class Sessions extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  private async createInternal(
    params: types.CreateAgentEngineSessionRequestParameters,
  ): Promise<types.AgentEngineSessionOperation> {
    let response: Promise<types.AgentEngineSessionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createAgentEngineSessionRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/sessions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSessionOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSessionOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  async delete(
    params: types.DeleteAgentEngineSessionRequestParameters,
  ): Promise<types.DeleteAgentEngineSessionOperation> {
    let response: Promise<types.DeleteAgentEngineSessionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteAgentEngineSessionRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteAgentEngineSessionOperation>;

      return response.then((resp) => {
        return resp as types.DeleteAgentEngineSessionOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  async get(
    params: types.GetAgentEngineSessionRequestParameters,
  ): Promise<types.Session> {
    let response: Promise<types.Session>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSessionRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Session>;

      return response.then((resp) => {
        return resp as types.Session;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async listInternal(
    params: types.ListAgentEngineSessionsRequestParameters,
  ): Promise<types.ListReasoningEnginesSessionsResponse> {
    let response: Promise<types.ListReasoningEnginesSessionsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listAgentEngineSessionsRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/sessions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListReasoningEnginesSessionsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListReasoningEnginesSessionsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async getSessionOperationInternal(
    params: types.GetAgentEngineSessionOperationParameters,
  ): Promise<types.AgentEngineSessionOperation> {
    let response: Promise<types.AgentEngineSessionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSessionOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSessionOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSessionOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }

  private async updateInternal(
    params: types.UpdateAgentEngineSessionRequestParameters,
  ): Promise<types.AgentEngineSessionOperation> {
    let response: Promise<types.AgentEngineSessionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.updateAgentEngineSessionRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'PATCH',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSessionOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSessionOperation;
      });
    } else {
      throw new Error('This method is only supported by the Vertex AI.');
    }
  }
}
