/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as genaiTypes from '@google/genai';

/** Applicable guideline for the optimize_prompt method. */
export declare interface ApplicableGuideline {
  applicableGuideline?: string;
  suggestedImprovement?: string;
  textBeforeChange?: string;
  textAfterChange?: string;
}

/** Response for the optimize_prompt method. */
export class ParsedResponse {
  optimizationType?: string;
  applicableGuidelines?: ApplicableGuideline[];
  originalPrompt?: string;
  suggestedPrompt?: string;
}

/** Response for the optimize_prompt method. */
export class ParsedResponseFewShot {
  suggestedModifications?: ApplicableGuideline[];
  originalSystemInstructions?: string;
  newSystemInstructions?: string;
}
