/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_agentengines_converters.js';
import {Sandboxes} from './sandboxes.js';
import {Sessions} from './sessions.js';
import * as types from './types.js';

export class AgentEngines extends BaseModule {
  public readonly sessions: Sessions;
  public readonly sandboxes: Sandboxes;

  /** Cached resource name of the lazily-created default agent engine. */
  private defaultAgentEngineName?: string;
  /** In-flight promise so concurrent callers share a single default agent engine. */
  private defaultAgentEnginePromise?: Promise<string>;

  constructor(private readonly apiClient: ApiClient) {
    super();
    this.sessions = new Sessions(apiClient);
    this.sandboxes = new Sandboxes(apiClient, () =>
      this.ensureDefaultAgentEngine(),
    );
  }

  /**
   * Returns the resource name of a shared "default" agent engine for this
   * project and location, creating it lazily if it does not exist. This backs
   * sandbox calls where the caller does not supply an agent engine name, so
   * repeated calls reuse one agent engine instead of creating many.
   */
  private async ensureDefaultAgentEngine(): Promise<string> {
    if (this.defaultAgentEngineName) {
      return this.defaultAgentEngineName;
    }
    if (!this.defaultAgentEnginePromise) {
      this.defaultAgentEnginePromise = this.resolveDefaultAgentEngine().catch(
        (e) => {
          // Allow a later call to retry if resolution failed.
          this.defaultAgentEnginePromise = undefined;
          throw e;
        },
      );
    }
    return this.defaultAgentEnginePromise;
  }

  private async resolveDefaultAgentEngine(): Promise<string> {
    const displayName = 'default-agent-platform-sandbox-host';
    // Reuse an existing default agent engine if one already exists.
    const listResponse = await this.listInternal({});
    const existing = listResponse.reasoningEngines?.find(
      (reasoningEngine) =>
        reasoningEngine.displayName === displayName && !!reasoningEngine.name,
    );
    if (existing?.name) {
      this.defaultAgentEngineName = existing.name;
      return existing.name;
    }
    // Otherwise create one and wait for the operation to complete.
    let operation = await this.createInternal({config: {displayName}});
    while (!operation.done) {
      await new Promise((resolve) => setTimeout(resolve, 5000));
      operation = await this.getAgentOperationInternal({
        operationName: operation.name!,
      });
    }
    if (operation.error) {
      throw new Error(
        `Failed to create default agent engine: ${JSON.stringify(
          operation.error,
        )}`,
      );
    }
    this.defaultAgentEngineName = operation.response!.name!;
    return this.defaultAgentEngineName;
  }

  async createInternal(
    params: types.CreateAgentEngineRequestParameters,
  ): Promise<types.AgentEngineOperation> {
    let response: Promise<types.AgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        'reasoningEngines',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineOperation>;

      return response.then((apiResponse) => {
        const resp = converters.agentEngineOperationFromVertex(apiResponse);

        return resp as types.AgentEngineOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async deleteInternal(
    params: types.DeleteAgentEngineRequestParameters,
  ): Promise<types.DeleteAgentEngineOperation> {
    let response: Promise<types.DeleteAgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteAgentEngineOperation>;

      return response.then((resp) => {
        return resp as types.DeleteAgentEngineOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getInternal(
    params: types.GetAgentEngineRequestParameters,
  ): Promise<types.ReasoningEngine> {
    let response: Promise<types.ReasoningEngine>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ReasoningEngine>;

      return response.then((apiResponse) => {
        const resp = converters.reasoningEngineFromVertex(apiResponse);

        return resp as types.ReasoningEngine;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListAgentEngineRequestParameters,
  ): Promise<types.ListReasoningEnginesResponse> {
    let response: Promise<types.ListReasoningEnginesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.listAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        'reasoningEngines',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListReasoningEnginesResponse>;

      return response.then((apiResponse) => {
        const resp =
          converters.listReasoningEnginesResponseFromVertex(apiResponse);
        const typedResp = new types.ListReasoningEnginesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getAgentOperationInternal(
    params: types.GetAgentEngineOperationParameters,
  ): Promise<types.AgentEngineOperation> {
    let response: Promise<types.AgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getAgentEngineOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineOperation>;

      return response.then((apiResponse) => {
        const resp = converters.agentEngineOperationFromVertex(apiResponse);

        return resp as types.AgentEngineOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async queryInternal(
    params: types.QueryAgentEngineRequestParameters,
  ): Promise<types.QueryReasoningEngineResponse> {
    let response: Promise<types.QueryReasoningEngineResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.queryAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}:query',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.QueryReasoningEngineResponse>;

      return response.then((resp) => {
        const typedResp = new types.QueryReasoningEngineResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async updateInternal(
    params: types.UpdateAgentEngineRequestParameters,
  ): Promise<types.AgentEngineOperation> {
    let response: Promise<types.AgentEngineOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.updateAgentEngineRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'PATCH',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineOperation>;

      return response.then((apiResponse) => {
        const resp = converters.agentEngineOperationFromVertex(apiResponse);

        return resp as types.AgentEngineOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
