/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_memorybanks_converters.js';
import {Memories} from './memories.js';
import * as types from './types.js';

export class MemoryBanks extends BaseModule {
  public readonly memories: Memories;

  constructor(private readonly apiClient: ApiClient) {
    super();
    this.memories = new Memories(apiClient);
  }

  async createInternal(
    params: types.CreateMemoryBankRequestParameters,
  ): Promise<types.MemoryBankOperation> {
    let response: Promise<types.MemoryBankOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.createMemoryBankRequestParametersToVertex();
      path = common.formatMap(
        'reasoningEngines',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.MemoryBankOperation>;

      return response.then((resp) => {
        return resp as types.MemoryBankOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async deleteInternal(
    params: types.DeleteMemoryBankRequestParameters,
  ): Promise<types.DeleteMemoryBankOperation> {
    let response: Promise<types.DeleteMemoryBankOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.deleteMemoryBankRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteMemoryBankOperation>;

      return response.then((resp) => {
        return resp as types.DeleteMemoryBankOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async ingestEventsInternal(
    params: types.IngestEventsRequestParameters,
  ): Promise<types.MemoryBankIngestEventsOperation> {
    let response: Promise<types.MemoryBankIngestEventsOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.ingestEventsRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories:ingestEvents',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.MemoryBankIngestEventsOperation>;

      return response.then((resp) => {
        return resp as types.MemoryBankIngestEventsOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getMemoryBankOperationInternal(
    params: types.GetMemoryBankOperationParameters,
  ): Promise<types.MemoryBankOperation> {
    let response: Promise<types.MemoryBankOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getMemoryBankOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.MemoryBankOperation>;

      return response.then((resp) => {
        return resp as types.MemoryBankOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
