/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as genaiTypes from '@google/genai';
import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_memoryrevisions_converters.js';
import * as types from './types.js';

export class MemoryRevisions extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  async get(
    params: types.GetAgentEngineMemoryRevisionRequestParameters,
  ): Promise<types.MemoryRevision> {
    let response: Promise<types.MemoryRevision>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineMemoryRevisionRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.MemoryRevision>;

      return response.then((resp) => {
        return resp as types.MemoryRevision;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListAgentEngineMemoryRevisionsRequestParameters,
  ): Promise<types.ListAgentEngineMemoryRevisionsResponse> {
    let response: Promise<types.ListAgentEngineMemoryRevisionsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listAgentEngineMemoryRevisionsRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/revisions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListAgentEngineMemoryRevisionsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListAgentEngineMemoryRevisionsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
