/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as genaiTypes from '@google/genai';
import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_memories_converters.js';
import {MemoryRevisions} from './memoryrevisions.js';
import * as types from './types.js';

export class Memories extends BaseModule {
  public readonly revisions: MemoryRevisions;

  constructor(private readonly apiClient: ApiClient) {
    super();
    this.revisions = new MemoryRevisions(apiClient);
  }

  async createInternal(
    params: types.CreateAgentEngineMemoryRequestParameters,
  ): Promise<types.AgentEngineMemoryOperation> {
    let response: Promise<types.AgentEngineMemoryOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createAgentEngineMemoryRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineMemoryOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineMemoryOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async delete(
    params: types.DeleteAgentEngineMemoryRequestParameters,
  ): Promise<types.DeleteAgentEngineMemoryOperation> {
    let response: Promise<types.DeleteAgentEngineMemoryOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteAgentEngineMemoryRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteAgentEngineMemoryOperation>;

      return response.then((resp) => {
        return resp as types.DeleteAgentEngineMemoryOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async generateInternal(
    params: types.GenerateAgentEngineMemoriesRequestParameters,
  ): Promise<types.AgentEngineGenerateMemoriesOperation> {
    let response: Promise<types.AgentEngineGenerateMemoriesOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.generateAgentEngineMemoriesRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories:generate',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineGenerateMemoriesOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineGenerateMemoriesOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async get(
    params: types.GetAgentEngineMemoryRequestParameters,
  ): Promise<types.Memory> {
    let response: Promise<types.Memory>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineMemoryRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Memory>;

      return response.then((resp) => {
        return resp as types.Memory;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async ingestEventsInternal(
    params: types.IngestEventsRequestParameters,
  ): Promise<types.MemoryBankIngestEventsOperation> {
    let response: Promise<types.MemoryBankIngestEventsOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.ingestEventsRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories:ingestEvents',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.MemoryBankIngestEventsOperation>;

      return response.then((resp) => {
        return resp as types.MemoryBankIngestEventsOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListAgentEngineMemoryRequestParameters,
  ): Promise<types.ListReasoningEnginesMemoriesResponse> {
    let response: Promise<types.ListReasoningEnginesMemoriesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listAgentEngineMemoryRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListReasoningEnginesMemoriesResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListReasoningEnginesMemoriesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getMemoryOperationInternal(
    params: types.GetAgentEngineMemoryOperationParameters,
  ): Promise<types.AgentEngineMemoryOperation> {
    let response: Promise<types.AgentEngineMemoryOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineMemoryOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineMemoryOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineMemoryOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getGenerateMemoriesOperationInternal(
    params: types.GetAgentEngineGenerateMemoriesOperationParameters,
  ): Promise<types.AgentEngineGenerateMemoriesOperation> {
    let response: Promise<types.AgentEngineGenerateMemoriesOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineGenerateMemoriesOperationParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineGenerateMemoriesOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineGenerateMemoriesOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async retrieveInternal(
    params: types.RetrieveAgentEngineMemoriesRequestParameters,
  ): Promise<types.RetrieveMemoriesResponse> {
    let response: Promise<types.RetrieveMemoriesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.retrieveAgentEngineMemoriesRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories:retrieve',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.RetrieveMemoriesResponse>;

      return response.then((resp) => {
        const typedResp = new types.RetrieveMemoriesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async retrieveProfiles(
    params: types.RetrieveMemoryProfilesRequestParameters,
  ): Promise<types.RetrieveProfilesResponse> {
    let response: Promise<types.RetrieveProfilesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.retrieveMemoryProfilesRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories:retrieveProfiles',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.RetrieveProfilesResponse>;

      return response.then((resp) => {
        const typedResp = new types.RetrieveProfilesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async rollbackInternal(
    params: types.RollbackAgentEngineMemoryRequestParameters,
  ): Promise<types.AgentEngineRollbackMemoryOperation> {
    let response: Promise<types.AgentEngineRollbackMemoryOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.rollbackAgentEngineMemoryRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}:rollback',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineRollbackMemoryOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineRollbackMemoryOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async updateInternal(
    params: types.UpdateAgentEngineMemoryRequestParameters,
  ): Promise<types.AgentEngineMemoryOperation> {
    let response: Promise<types.AgentEngineMemoryOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.updateAgentEngineMemoryRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'PATCH',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineMemoryOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineMemoryOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async purgeInternal(
    params: types.PurgeAgentEngineMemoriesRequestParameters,
  ): Promise<types.AgentEnginePurgeMemoriesOperation> {
    let response: Promise<types.AgentEnginePurgeMemoriesOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.purgeAgentEngineMemoriesRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/memories:purge',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEnginePurgeMemoriesOperation>;

      return response.then((resp) => {
        return resp as types.AgentEnginePurgeMemoriesOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
