/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as genaiTypes from '@google/genai';
import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_prompts_converters.js';
import * as types from './types.js';

export class Prompts extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  /* eslint-disable @typescript-eslint/no-explicit-any */
  private async _wait_for_operation(
    operation: any,
    timeout: number,
  ): Promise<string> {
    let done = false;
    let promptDatasetOperation: any;

    const responseOperationName = operation.name;
    if (!responseOperationName) {
      throw new Error('Invalid operation name.');
    }

    const datasetId = responseOperationName
      .split('/datasets/')[1]
      .split('/')[0];
    const operationId = responseOperationName.split('/').pop();

    if (!operationId) {
      throw new Error('Invalid operation name.');
    }

    const startTime = Date.now();
    let sleepDuration = 5000; // ms
    const waitMultiplier = 2;
    const maxWaitTime = 60000; // ms
    let previousTime = Date.now();

    while (!done) {
      if (Date.now() - startTime > timeout * 1000) {
        throw new Error(
          `Create prompt operation did not complete within the specified timeout of ${timeout} seconds.`,
        );
      }
      const currentTime = Date.now();
      if (currentTime - previousTime >= sleepDuration) {
        sleepDuration = Math.min(sleepDuration * waitMultiplier, maxWaitTime);
        previousTime = currentTime;
      }
      await new Promise((resolve) => setTimeout(resolve, sleepDuration));

      promptDatasetOperation = await this.getDatasetOperationInternal({
        datasetId: datasetId,
        operationId: operationId,
      });

      done = promptDatasetOperation.done || false;
    }

    if (
      !promptDatasetOperation ||
      !promptDatasetOperation.response ||
      !promptDatasetOperation.response['name']
    ) {
      throw new Error('Error creating prompt version resource.');
    }
    if (promptDatasetOperation.error) {
      throw new Error(
        `Error creating prompt version resource: ${JSON.stringify(promptDatasetOperation.error)}`,
      );
    }
    return promptDatasetOperation.response['name'] as string;
  }

  private _createDatasetMetadataFromPrompt(
    prompt: any,
    variables?: Record<string, any>[],
  ): any {
    const promptMetadata: any = {};
    const promptApiSchema: any = {};

    promptApiSchema.multimodalPrompt = {
      promptMessage: prompt.promptData,
    };

    promptApiSchema.apiSchemaVersion = '1.0.0';
    promptMetadata.hasPromptVariable = !!variables;

    if (variables) {
      const promptExecutionList: any[] = [];
      for (const promptVar of variables) {
        const promptInstanceExecution: any = {arguments: {}};
        for (const [key, val] of Object.entries(promptVar)) {
          promptInstanceExecution.arguments[key] = {
            partList: {parts: [val]},
          };
        }
        promptExecutionList.push(promptInstanceExecution);
      }
      promptApiSchema.executions = promptExecutionList;
    }

    if (promptApiSchema.multimodalPrompt.promptMessage) {
      const promptMessage = {...promptApiSchema.multimodalPrompt.promptMessage};
      delete promptMessage.variables;
      promptApiSchema.multimodalPrompt.promptMessage = promptMessage;
    }

    promptMetadata.promptApiSchema = promptApiSchema;
    promptMetadata.promptType = 'multimodal_freeform';

    return promptMetadata;
  }

  private _createPromptFromDatasetMetadata(dataset: any): any {
    const prompt: any = {};
    if (!dataset.metadata || !dataset.metadata.promptApiSchema) {
      return prompt;
    }
    const apiSchema = dataset.metadata.promptApiSchema;

    if (
      apiSchema.multimodalPrompt &&
      apiSchema.multimodalPrompt.promptMessage
    ) {
      prompt.promptData = apiSchema.multimodalPrompt.promptMessage;
    }

    if (apiSchema.executions) {
      const variables: Record<string, any>[] = [];
      for (const execution of apiSchema.executions) {
        const promptVar: Record<string, any> = {};
        if (execution.arguments) {
          for (const [key, val] of Object.entries(execution.arguments)) {
            if (val && (val as any).partList && (val as any).partList.parts) {
              promptVar[key] = (val as any).partList.parts[0];
            }
          }
        }
        variables.push(promptVar);
      }
      if (prompt.promptData) {
        prompt.promptData.variables = variables;
      }
    }

    if (dataset.modelReference) {
      if (!prompt.promptData) {
        prompt.promptData = {};
      }
      prompt.promptData.model = dataset.modelReference;
    }

    return prompt;
  }

  private _raiseForInvalidPrompt(prompt: any): void {
    if (!prompt.promptData) {
      throw new Error('Prompt data must be provided.');
    }
    if (!prompt.promptData.contents) {
      throw new Error('Prompt contents must be provided.');
    }
    if (!prompt.promptData.model) {
      throw new Error('Model name must be provided.');
    }
    if (prompt.promptData.contents && prompt.promptData.contents.length > 1) {
      throw new Error('Multi-turn prompts are not currently supported.');
    }
  }

  async create(params: {prompt: any; config?: any}): Promise<any> {
    const {prompt, config} = params;

    this._raiseForInvalidPrompt(prompt);

    const promptMetadata = this._createDatasetMetadataFromPrompt(
      prompt,
      prompt.promptData.variables,
    );

    const createPromptDatasetOperation =
      await this.createDatasetResourceInternal({
        name: `projects/${this.apiClient.clientOptions.project}/locations/${this.apiClient.clientOptions.location}`,
        displayName: config?.promptDisplayName || `prompt_${Date.now()}`,
        metadataSchemaUri:
          'gs://google-cloud-aiplatform/schema/dataset/metadata/text_prompt_1.0.0.yaml',
        metadata: promptMetadata,
        modelReference: prompt.promptData.model,
        encryptionSpec: config?.encryptionSpec,
      });

    const datasetResourceName = await this._wait_for_operation(
      createPromptDatasetOperation,
      config?.timeout || 90,
    );

    const datasetId = datasetResourceName.split('/').pop();
    if (!datasetId) {
      throw new Error('Invalid dataset resource name.');
    }

    const datasetResource = await this.getDatasetResourceInternal({
      name: datasetId,
    });

    prompt._dataset = datasetResource;
    return prompt;
  }

  async createVersion(params: {prompt: any; config?: any}): Promise<any> {
    const {prompt, config} = params;

    this._raiseForInvalidPrompt(prompt);

    const promptMetadata = this._createDatasetMetadataFromPrompt(
      prompt,
      prompt.promptData.variables,
    );

    const createPromptDatasetOperation =
      await this.createDatasetResourceInternal({
        name: `projects/${this.apiClient.clientOptions.project}/locations/${this.apiClient.clientOptions.location}`,
        displayName: config?.promptDisplayName || `prompt_${Date.now()}`,
        metadataSchemaUri:
          'gs://google-cloud-aiplatform/schema/dataset/metadata/text_prompt_1.0.0.yaml',
        metadata: promptMetadata,
        modelReference: prompt.promptData.model,
        encryptionSpec: config?.encryptionSpec,
      });

    const datasetResourceName = await this._wait_for_operation(
      createPromptDatasetOperation,
      config?.timeout || 90,
    );

    const datasetId = datasetResourceName.split('/').pop();
    if (!datasetId) {
      throw new Error('Invalid dataset resource name.');
    }

    const datasetResource = await this.getDatasetResourceInternal({
      name: datasetId,
    });

    prompt._dataset = datasetResource;

    const createDatasetVersionOperation =
      await this.createDatasetVersionResourceInternal({
        datasetName: datasetId,
        displayName:
          config?.versionDisplayName || `prompt_version_${Date.now()}`,
      });

    const datasetVersionResourceName = await this._wait_for_operation(
      createDatasetVersionOperation,
      config?.timeout || 90,
    );

    const versionId = datasetVersionResourceName.split('/').pop();
    if (!versionId) {
      throw new Error('Invalid dataset version resource name.');
    }

    const datasetVersionResource = await this.getDatasetVersionResourceInternal(
      {
        datasetId: datasetId,
        datasetVersionId: versionId,
      },
    );

    const updatedPrompt = this._createPromptFromDatasetMetadata(
      datasetVersionResource,
    );
    updatedPrompt._dataset = datasetResource;
    updatedPrompt._dataset_version = datasetVersionResource;

    return updatedPrompt;
  }

  async get(params: {promptId: string; config?: any}): Promise<any> {
    const {promptId} = params;

    const promptDatasetResource = await this.getDatasetResourceInternal({
      name: promptId,
    });
    const prompt = this._createPromptFromDatasetMetadata(promptDatasetResource);
    prompt._dataset = promptDatasetResource;

    return prompt;
  }

  async getVersion(params: {
    promptId: string;
    versionId: string;
    config?: any;
  }): Promise<any> {
    const {promptId, versionId} = params;

    const promptDatasetResource = await this.getDatasetResourceInternal({
      name: promptId,
    });
    const prompt = this._createPromptFromDatasetMetadata(promptDatasetResource);
    prompt._dataset = promptDatasetResource;

    const promptVersionResource = await this.getDatasetVersionResourceInternal({
      datasetId: promptId,
      datasetVersionId: versionId,
    });
    prompt._dataset_version = promptVersionResource;

    return prompt;
  }

  async list(params?: {config?: any}): Promise<any[]> {
    const config = params?.config;
    const response = await this.listPromptsInternal({config});
    const promptRefs: any[] = [];

    if (response.datasets) {
      for (const dataset of response.datasets) {
        if (dataset.name) {
          promptRefs.push({
            model: dataset.modelReference,
            promptId: dataset.name.split('/').pop(),
          });
        }
      }
    }
    return promptRefs;
  }

  async listVersions(params: {promptId: string; config?: any}): Promise<any[]> {
    const {promptId, config} = params;
    const response = await this.listVersionsInternal({
      datasetId: promptId,
      config,
    });
    const versionRefs: any[] = [];

    if (response.datasetVersions) {
      for (const datasetVersion of response.datasetVersions) {
        if (datasetVersion.name) {
          versionRefs.push({
            model: datasetVersion.modelReference,
            versionId: datasetVersion.name.split('/').pop(),
            promptId: promptId,
          });
        }
      }
    }
    return versionRefs;
  }

  private async _wait_for_project_operation(
    operation: any,
    timeout: number,
  ): Promise<void> {
    let done = false;
    const startTime = Date.now();
    let sleepDuration = 5000; // ms
    const waitMultiplier = 2;
    const maxWaitTime = 60000; // ms
    let previousTime = Date.now();

    if (!operation.name) {
      throw new Error('Invalid operation name.');
    }

    while (!done) {
      if (Date.now() - startTime > timeout * 1000) {
        throw new Error(
          `Delete operation did not complete within the specified timeout of ${timeout} seconds.`,
        );
      }
      const currentTime = Date.now();
      if (currentTime - previousTime >= sleepDuration) {
        sleepDuration = Math.min(sleepDuration * waitMultiplier, maxWaitTime);
        previousTime = currentTime;
      }
      await new Promise((resolve) => setTimeout(resolve, sleepDuration));

      const response = await this.apiClient.request({
        path: operation.name,
        httpMethod: 'GET',
      });
      const opStatus = (await response.json()) as any;
      done = opStatus.done || false;

      if (opStatus.error) {
        throw new Error(
          `Error in delete operation: ${JSON.stringify(opStatus.error)}`,
        );
      }
    }
  }

  async delete(params: {promptId: string; config?: any}): Promise<void> {
    const {promptId, config} = params;

    const deletePromptOperation = await this.deleteDatasetInternal({
      promptId: promptId,
      config: config,
    });

    await this._wait_for_project_operation(
      deletePromptOperation,
      config?.timeout || 90,
    );
  }

  async deleteVersion(params: {
    promptId: string;
    versionId: string;
    config?: any;
  }): Promise<void> {
    const {promptId, versionId, config} = params;

    const deleteVersionOperation = await this.deleteDatasetVersionInternal({
      promptId: promptId,
      versionId: versionId,
      config: config,
    });

    await this._wait_for_project_operation(
      deleteVersionOperation,
      config?.timeout || 90,
    );
  }

  async restoreVersion(params: {
    promptId: string;
    versionId: string;
    config?: any;
  }): Promise<any> {
    const {promptId, versionId} = params;

    const restorePromptOperation = await this.restoreVersionInternal({
      datasetId: promptId,
      versionId: versionId,
    });

    await this._wait_for_project_operation(restorePromptOperation, 90);

    const datasetVersionResource = await this.getDatasetVersionResourceInternal(
      {
        datasetId: promptId,
        datasetVersionId: versionId,
      },
    );

    const updatedPrompt = this._createPromptFromDatasetMetadata(
      datasetVersionResource,
    );
    updatedPrompt._dataset_version = datasetVersionResource;
    return updatedPrompt;
  }

  async update(params: {
    promptId: string;
    prompt: any;
    config?: any;
  }): Promise<any> {
    const {promptId, prompt, config} = params;

    this._raiseForInvalidPrompt(prompt);

    const promptMetadata = this._createDatasetMetadataFromPrompt(
      prompt,
      prompt.promptData.variables,
    );

    if (!prompt.promptData) {
      throw new Error('Prompt data is required to update a prompt.');
    }

    const updatedDatasetResource = await this.updateDatasetResourceInternal({
      name: `projects/${this.apiClient.clientOptions.project}/locations/${this.apiClient.clientOptions.location}`,
      datasetId: promptId,
      displayName: config?.promptDisplayName,
      metadata: promptMetadata,
      modelReference: prompt.promptData.model,
      encryptionSpec: config?.encryptionSpec,
      config: config,
    });

    const datasetId = updatedDatasetResource.name?.split('/').pop();
    if (!datasetId) {
      throw new Error('Failed to update dataset resource or get dataset ID.');
    }

    const createDatasetVersionOperation =
      await this.createDatasetVersionResourceInternal({
        datasetName: datasetId,
        displayName:
          config?.versionDisplayName || `prompt_version_${Date.now()}`,
      });

    const datasetVersionResourceName = await this._wait_for_operation(
      createDatasetVersionOperation,
      config?.timeout || 90,
    );

    const versionId = datasetVersionResourceName.split('/').pop();

    const datasetVersionResource = await this.getDatasetVersionResourceInternal(
      {
        datasetId: datasetId,
        datasetVersionId: versionId,
      },
    );

    const updatedPrompt = this._createPromptFromDatasetMetadata(
      datasetVersionResource,
    );
    updatedPrompt._dataset = updatedDatasetResource;
    updatedPrompt._dataset_version = datasetVersionResource;

    return updatedPrompt;
  }

  private async createDatasetResourceInternal(
    params: types.CreateDatasetParameters,
  ): Promise<types.DatasetOperation> {
    let response: Promise<types.DatasetOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.createDatasetParametersToVertex(params);
      path = common.formatMap(
        'datasets',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetOperation>;

      return response.then((resp) => {
        return resp as types.DatasetOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async createDatasetVersionResourceInternal(
    params: types.CreateDatasetVersionParameters,
  ): Promise<types.DatasetOperation> {
    let response: Promise<types.DatasetOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.createDatasetVersionParametersToVertex(params);
      path = common.formatMap(
        'datasets/{name}/datasetVersions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetOperation>;

      return response.then((resp) => {
        return resp as types.DatasetOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getDatasetResourceInternal(
    params: types.GetDatasetParameters,
  ): Promise<types.Dataset> {
    let response: Promise<types.Dataset>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getDatasetParametersToVertex(params);
      path = common.formatMap(
        'datasets/{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Dataset>;

      return response.then((resp) => {
        return resp as types.Dataset;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getDatasetVersionResourceInternal(
    params: types.GetDatasetVersionParameters,
  ): Promise<types.DatasetVersion> {
    let response: Promise<types.DatasetVersion>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getDatasetVersionParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions/{dataset_version_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetVersion>;

      return response.then((resp) => {
        return resp as types.DatasetVersion;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getDatasetOperationInternal(
    params: types.GetDatasetOperationParameters,
  ): Promise<types.DatasetOperation> {
    let response: Promise<types.DatasetOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getDatasetOperationParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/operations/{operation_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetOperation>;

      return response.then((resp) => {
        return resp as types.DatasetOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async listPromptsInternal(
    params: types.ListDatasetsRequestParameters,
  ): Promise<types.ListDatasetsResponse> {
    let response: Promise<types.ListDatasetsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.listDatasetsRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListDatasetsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListDatasetsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async listVersionsInternal(
    params: types.ListDatasetVersionsRequestParameters,
  ): Promise<types.ListDatasetVersionsResponse> {
    let response: Promise<types.ListDatasetVersionsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listDatasetVersionsRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListDatasetVersionsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListDatasetVersionsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async deleteDatasetInternal(
    params: types.DeleteDatasetRequestParameters,
  ): Promise<types.DeletePromptOperation> {
    let response: Promise<types.DeletePromptOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.deleteDatasetRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeletePromptOperation>;

      return response.then((resp) => {
        return resp as types.DeletePromptOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async deleteDatasetVersionInternal(
    params: types.DeletePromptVersionRequestParameters,
  ): Promise<types.DeletePromptVersionOperation> {
    let response: Promise<types.DeletePromptVersionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deletePromptVersionRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions/{version_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeletePromptVersionOperation>;

      return response.then((resp) => {
        return resp as types.DeletePromptVersionOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async restoreVersionInternal(
    params: types.RestoreVersionRequestParameters,
  ): Promise<types.RestoreVersionOperation> {
    let response: Promise<types.RestoreVersionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.restoreVersionRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions/{version_id}:restore',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.RestoreVersionOperation>;

      return response.then((resp) => {
        return resp as types.RestoreVersionOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async updateDatasetResourceInternal(
    params: types.UpdateDatasetParameters,
  ): Promise<types.Dataset> {
    let response: Promise<types.Dataset>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.updateDatasetParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'PATCH',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Dataset>;

      return response.then((resp) => {
        return resp as types.Dataset;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
