/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_prompts_converters.js';
import * as types from './types.js';

export class Prompts extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  private static readonly _DEFAULT_TIMEOUT = 90;
  private static readonly _DEFAULT_MAX_WAIT_TIME = 60;

  /* eslint-disable @typescript-eslint/no-explicit-any */
  private async _waitForOperation(
    operation: any,
    timeout = Prompts._DEFAULT_TIMEOUT,
    maxWaitTime = Prompts._DEFAULT_MAX_WAIT_TIME * 1000,
  ): Promise<string> {
    let done = false;
    let promptDatasetOperation: any;

    const responseOperationName = operation?.name;
    if (!responseOperationName) {
      throw new Error('Invalid operation name.');
    }

    const parts = responseOperationName.split('/datasets/');
    if (parts.length < 2) {
      throw new Error(
        `Unexpected operation name format: ${responseOperationName}`,
      );
    }
    const datasetId = parts[1].split('/')[0];
    const operationId = responseOperationName.split('/').pop();

    if (!datasetId || !operationId) {
      throw new Error('Invalid operation name.');
    }

    const startTime = Date.now();
    let sleepDuration = 5000; // ms

    while (!done) {
      if (Date.now() - startTime > timeout * 1000) {
        throw new Error(
          `Operation did not complete within the specified timeout of ${timeout} seconds.`,
        );
      }
      await new Promise((resolve) => setTimeout(resolve, sleepDuration));
      sleepDuration = Math.min(sleepDuration * 2, maxWaitTime);

      promptDatasetOperation = await this.getDatasetOperationInternal({
        datasetId,
        operationId,
      });

      done = promptDatasetOperation?.done || false;
    }

    if (promptDatasetOperation?.error) {
      throw new Error(
        `Error in dataset operation: ${JSON.stringify(promptDatasetOperation.error)}`,
      );
    }
    if (!promptDatasetOperation?.response?.['name']) {
      throw new Error('Error in dataset operation: response name not found.');
    }
    return promptDatasetOperation.response['name'] as string;
  }

  private async _waitForProjectOperation(
    operation: any,
    timeout = Prompts._DEFAULT_TIMEOUT,
    maxWaitTime = Prompts._DEFAULT_MAX_WAIT_TIME * 1000,
  ): Promise<void> {
    let done = false;
    const startTime = Date.now();
    let sleepDuration = 5000; // ms

    if (!operation?.name) {
      throw new Error('Invalid operation name.');
    }

    while (!done) {
      if (Date.now() - startTime > timeout * 1000) {
        throw new Error(
          `Operation did not complete within the specified timeout of ${timeout} seconds.`,
        );
      }
      await new Promise((resolve) => setTimeout(resolve, sleepDuration));
      sleepDuration = Math.min(sleepDuration * 2, maxWaitTime);

      const operationId = operation.name.split('/').pop();
      if (!operationId) {
        throw new Error('Invalid operation name.');
      }
      const response = await this.apiClient.request({
        path: `operations/${operationId}`,
        httpMethod: 'GET',
      });
      const opStatus = (await response.json()) as any;
      done = opStatus?.done || false;

      if (opStatus?.error) {
        throw new Error(
          `Error in operation: ${JSON.stringify(opStatus.error)}`,
        );
      }
    }
  }

  private _raiseForInvalidPrompt(prompt: any): void {
    if (!prompt || !prompt.promptData) {
      throw new Error('Prompt data must be provided.');
    }
    if (
      !prompt.promptData.contents ||
      prompt.promptData.contents.length === 0
    ) {
      throw new Error('Prompt contents must be provided.');
    }
    if (!prompt.promptData.model) {
      throw new Error('Model name must be provided.');
    }
    if (prompt.promptData.contents && prompt.promptData.contents.length > 1) {
      throw new Error('Multi-turn prompts are not currently supported.');
    }
  }

  private _createDatasetMetadataFromPrompt(
    prompt: any,
    variables?: Record<string, any>[],
  ): any {
    const promptMetadata: any = {};
    const promptApiSchema: any = {};

    promptApiSchema.multimodalPrompt = {
      promptMessage: prompt.promptData,
    };
    promptApiSchema.apiSchemaVersion = '1.0.0';
    promptMetadata.hasPromptVariable = Boolean(
      variables && variables.length > 0,
    );

    if (variables && variables.length > 0) {
      const promptExecutionList: any[] = [];
      for (const promptVar of variables) {
        const promptInstanceExecution: any = {arguments: {}};
        for (const [key, val] of Object.entries(promptVar)) {
          promptInstanceExecution.arguments[key] = {
            partList: {parts: [val]},
          };
        }
        promptExecutionList.push(promptInstanceExecution);
      }
      promptApiSchema.executions = promptExecutionList;
    }

    if (promptApiSchema.multimodalPrompt.promptMessage) {
      const promptMessage = {...promptApiSchema.multimodalPrompt.promptMessage};
      delete promptMessage.variables;
      promptApiSchema.multimodalPrompt.promptMessage = promptMessage;
    }

    promptMetadata.promptApiSchema = promptApiSchema;
    promptMetadata.promptType = 'multimodal_freeform';

    return promptMetadata;
  }

  private _createPromptFromDatasetMetadata(dataset: any): any {
    const prompt: any = {};
    if (!dataset?.metadata?.promptApiSchema) {
      return prompt;
    }
    const apiSchema = dataset.metadata.promptApiSchema;

    if (apiSchema.multimodalPrompt?.promptMessage) {
      prompt.promptData = {...apiSchema.multimodalPrompt.promptMessage};
    }

    if (apiSchema.executions) {
      const variables: Record<string, any>[] = [];
      for (const execution of apiSchema.executions) {
        const promptVar: Record<string, any> = {};
        if (execution.arguments) {
          for (const [key, val] of Object.entries(execution.arguments)) {
            if (val && (val as any).partList?.parts) {
              promptVar[key] = (val as any).partList.parts[0];
            }
          }
        }
        variables.push(promptVar);
      }
      if (prompt.promptData) {
        prompt.promptData.variables = variables;
      }
    }

    if (dataset.modelReference) {
      if (!prompt.promptData) {
        prompt.promptData = {};
      }
      prompt.promptData.model = dataset.modelReference;
    }

    return prompt;
  }

  /**
   * Creates a new prompt resource (dataset) and an initial prompt version.
   *
   * Note: To create a new version of an existing prompt, use the `update` method instead.
   *
   * @param params - The parameters for creating a new prompt version.
   * @param params.prompt - The prompt to create.
   * @param params.config - Optional configuration for creating the prompt and version.
   * @returns A Promise resolving to the created Prompt object with its associated Dataset and DatasetVersion resources.
   */
  async createVersion(params: {
    prompt: types.Prompt;
    config?: types.CreatePromptVersionConfig;
  }): Promise<types.Prompt> {
    const {prompt, config} = params;
    this._raiseForInvalidPrompt(prompt);

    const promptMetadata = this._createDatasetMetadataFromPrompt(
      prompt,
      prompt.promptData?.variables,
    );

    const project = this.apiClient.clientOptions.project;
    const location = this.apiClient.clientOptions.location;
    if (!project || !location) {
      throw new Error(
        'Project and location must be specified in client options.',
      );
    }

    const createPromptDatasetOperation =
      await this.createDatasetResourceInternal({
        name: `projects/${project}/locations/${location}`,
        displayName: config?.promptDisplayName || `prompt_${Date.now()}`,
        metadataSchemaUri:
          'gs://google-cloud-aiplatform/schema/dataset/metadata/text_prompt_1.0.0.yaml',
        metadata: promptMetadata,
        modelReference: prompt.promptData?.model,
        encryptionSpec: config?.encryptionSpec,
        config,
      });

    const datasetResourceName = await this._waitForOperation(
      createPromptDatasetOperation,
      config?.timeout ?? Prompts._DEFAULT_TIMEOUT,
      (config?.maxWaitTime ?? Prompts._DEFAULT_MAX_WAIT_TIME) * 1000,
    );

    const datasetId = datasetResourceName.split('/').pop();
    if (!datasetId) {
      throw new Error('Invalid dataset resource name.');
    }

    const datasetResource = await this.getDatasetResourceInternal({
      name: datasetId,
    });

    const createDatasetVersionOperation =
      await this.createDatasetVersionResourceInternal({
        datasetName: datasetId,
        displayName:
          config?.versionDisplayName || `prompt_version_${Date.now()}`,
        config,
      });

    const datasetVersionResourceName = await this._waitForOperation(
      createDatasetVersionOperation,
      config?.timeout ?? Prompts._DEFAULT_TIMEOUT,
      (config?.maxWaitTime ?? Prompts._DEFAULT_MAX_WAIT_TIME) * 1000,
    );

    const versionId = datasetVersionResourceName.split('/').pop();
    if (!versionId) {
      throw new Error('Invalid dataset version resource name.');
    }

    const datasetVersionResource = await this.getDatasetVersionResourceInternal(
      {
        datasetId,
        datasetVersionId: versionId,
      },
    );

    const updatedPrompt = this._createPromptFromDatasetMetadata(
      datasetVersionResource,
    );
    (updatedPrompt as any)._dataset = datasetResource;
    (updatedPrompt as any)._dataset_version = datasetVersionResource;

    return updatedPrompt;
  }

  /**
   * Retrieves a prompt resource from Vertex AI by ID.
   *
   * @param params - The parameters for getting a prompt.
   * @param params.promptId - The ID of the prompt dataset resource to retrieve.
   * @param params.config - Optional configuration for retrieving the prompt.
   * @returns A Promise resolving to the retrieved Prompt object.
   */
  async get(params: {
    promptId: string;
    config?: types.GetPromptConfig;
  }): Promise<types.Prompt> {
    const {promptId, config} = params;
    const promptDatasetResource = await this.getDatasetResourceInternal({
      name: promptId,
      config,
    });
    const prompt = this._createPromptFromDatasetMetadata(promptDatasetResource);
    (prompt as any)._dataset = promptDatasetResource;
    return prompt;
  }

  /**
   * Retrieves a specific version of a prompt resource from Vertex AI.
   *
   * @param params - The parameters for getting a prompt version.
   * @param params.promptId - The ID of the parent prompt dataset resource.
   * @param params.versionId - The ID of the specific prompt version resource to retrieve.
   * @param params.config - Optional configuration for retrieving the prompt version.
   * @returns A Promise resolving to the retrieved Prompt object containing the specified version metadata.
   */
  async getVersion(params: {
    promptId: string;
    versionId: string;
    config?: types.GetPromptConfig;
  }): Promise<types.Prompt> {
    const {promptId, versionId, config} = params;
    const promptDatasetResource = await this.getDatasetResourceInternal({
      name: promptId,
      config,
    });
    const prompt = this._createPromptFromDatasetMetadata(promptDatasetResource);
    (prompt as any)._dataset = promptDatasetResource;

    const promptVersionResource = await this.getDatasetVersionResourceInternal({
      datasetId: promptId,
      datasetVersionId: versionId,
      config,
    });
    (prompt as any)._dataset_version = promptVersionResource;
    return prompt;
  }

  /**
   * Lists prompt resources in the configured project and location.
   *
   * @param params - Optional parameters and configuration for listing prompts.
   * @param params.config - Optional configuration and filter options for listing prompts.
   * @returns A Promise resolving to an array of PromptRef references to the listed prompt datasets.
   */
  async list(
    params: {config?: types.ListPromptsConfig} = {},
  ): Promise<types.PromptRef[]> {
    let config: any = params.config ? {...params.config} : {};
    let response = await this.listPromptsInternal({config});
    const promptRefs: types.PromptRef[] = [];
    let hasNextPage = true;
    while (hasNextPage) {
      if (response.datasets) {
        for (const dataset of response.datasets) {
          if (dataset.name) {
            promptRefs.push({
              model: dataset.modelReference,
              promptId: dataset.name.split('/').pop(),
            });
          }
        }
      }
      if (!response.nextPageToken) {
        hasNextPage = false;
        break;
      }
      config = {...config, pageToken: response.nextPageToken};
      response = await this.listPromptsInternal({config});
    }
    return promptRefs;
  }

  /**
   * Lists all versions of a specific prompt resource.
   *
   * @param params - The parameters for listing prompt versions.
   * @param params.promptId - The ID of the parent prompt dataset resource to list versions for.
   * @param params.config - Optional configuration and filter options for listing prompt versions.
   * @returns A Promise resolving to an array of PromptVersionRef references to the listed prompt versions.
   */
  async listVersions(params: {
    promptId: string;
    config?: types.ListPromptsConfig;
  }): Promise<types.PromptVersionRef[]> {
    const {promptId} = params;
    let config: any = params.config ? {...params.config} : {};
    let response = await this.listVersionsInternal({
      datasetId: promptId,
      config,
    });
    const versionRefs: types.PromptVersionRef[] = [];
    let hasNextPage = true;
    while (hasNextPage) {
      if (response.datasetVersions) {
        for (const datasetVersion of response.datasetVersions) {
          if (datasetVersion.name) {
            versionRefs.push({
              model: datasetVersion.modelReference,
              versionId: datasetVersion.name.split('/').pop(),
              promptId,
            });
          }
        }
      }
      if (!response.nextPageToken) {
        hasNextPage = false;
        break;
      }
      config = {...config, pageToken: response.nextPageToken};
      response = await this.listVersionsInternal({
        datasetId: promptId,
        config,
      });
    }
    return versionRefs;
  }

  /**
   * Deletes a prompt resource and all of its associated versions.
   *
   * @param params - The parameters for deleting a prompt.
   * @param params.promptId - The ID of the prompt dataset resource to delete.
   * @param params.config - Optional configuration and timeout options for delete operation.
   * @returns A Promise that resolves once the prompt has been deleted.
   */
  async delete(params: {
    promptId: string;
    config?: types.DeletePromptConfig;
  }): Promise<void> {
    const {promptId, config} = params;
    const deletePromptOperation = await this.deleteDatasetInternal({
      promptId,
      config,
    });
    await this._waitForProjectOperation(
      deletePromptOperation,
      config?.timeout ?? Prompts._DEFAULT_TIMEOUT,
      (config?.maxWaitTime ?? Prompts._DEFAULT_MAX_WAIT_TIME) * 1000,
    );
  }

  /**
   * Deletes a specific version of a prompt resource.
   *
   * @param params - The parameters for deleting a prompt version.
   * @param params.promptId - The ID of the parent prompt dataset resource.
   * @param params.versionId - The ID of the specific prompt version resource to delete.
   * @param params.config - Optional configuration and timeout options for delete operation.
   * @returns A Promise that resolves once the prompt version has been deleted.
   */
  async deleteVersion(params: {
    promptId: string;
    versionId: string;
    config?: types.DeletePromptConfig;
  }): Promise<void> {
    const {promptId, versionId, config} = params;
    const deleteVersionOperation = await this.deleteDatasetVersionInternal({
      promptId,
      versionId,
      config,
    });
    await this._waitForProjectOperation(
      deleteVersionOperation,
      config?.timeout ?? Prompts._DEFAULT_TIMEOUT,
      (config?.maxWaitTime ?? Prompts._DEFAULT_MAX_WAIT_TIME) * 1000,
    );
  }

  /**
   * Restores a specific prompt version to be the latest default version of the prompt.
   *
   * @param params - The parameters for restoring a prompt version.
   * @param params.promptId - The ID of the parent prompt dataset resource.
   * @param params.versionId - The ID of the specific prompt version resource to restore.
   * @param params.config - Optional configuration for restoring the prompt version.
   * @returns A Promise resolving to the Prompt object representing the restored latest version.
   */
  async restoreVersion(params: {
    promptId: string;
    versionId: string;
    config?: types.RestoreVersionConfig;
  }): Promise<types.Prompt> {
    const {promptId, versionId, config} = params;
    const restorePromptOperation = await this.restoreVersionInternal({
      datasetId: promptId,
      versionId,
      config,
    });
    await this._waitForProjectOperation(
      restorePromptOperation,
      config?.timeout ?? Prompts._DEFAULT_TIMEOUT,
      (config?.maxWaitTime ?? Prompts._DEFAULT_MAX_WAIT_TIME) * 1000,
    );
    const datasetVersionResource = await this.getDatasetVersionResourceInternal(
      {
        datasetId: promptId,
        datasetVersionId: versionId,
      },
    );
    const updatedPrompt = this._createPromptFromDatasetMetadata(
      datasetVersionResource,
    );
    (updatedPrompt as any)._dataset_version = datasetVersionResource;
    return updatedPrompt;
  }

  /**
   * Updates an existing prompt dataset and creates a new prompt version for it.
   *
   * @param params - The parameters for updating the prompt.
   * @param params.promptId - The ID of the existing prompt dataset resource to update and add a version to.
   * @param params.prompt - The updated prompt content.
   * @param params.config - Optional configuration for updating the prompt and version.
   * @returns A Promise resolving to the updated Prompt object with its associated Dataset and DatasetVersion resources.
   */
  async update(params: {
    promptId: string;
    prompt: types.Prompt;
    config?: types.UpdatePromptConfig;
  }): Promise<types.Prompt> {
    const {promptId, prompt, config} = params;
    this._raiseForInvalidPrompt(prompt);

    if (!prompt.promptData) {
      throw new Error('Prompt data is required to update a prompt.');
    }

    const promptMetadata = this._createDatasetMetadataFromPrompt(
      prompt,
      prompt.promptData.variables,
    );

    const project = this.apiClient.clientOptions.project;
    const location = this.apiClient.clientOptions.location;
    if (!project || !location) {
      throw new Error(
        'Project and location must be specified in client options.',
      );
    }

    const updatedDatasetResource = await this.updateDatasetResourceInternal({
      name: `projects/${project}/locations/${location}/datasets/${promptId}`,
      datasetId: promptId,
      displayName: config?.promptDisplayName,
      metadata: promptMetadata,
      modelReference: prompt.promptData.model,
      encryptionSpec: config?.encryptionSpec,
      config,
    });

    if (!updatedDatasetResource.name) {
      throw new Error(
        'Failed to update dataset resource: resource name missing.',
      );
    }

    const datasetId = updatedDatasetResource.name.split('/').pop();
    if (!datasetId) {
      throw new Error('Failed to parse dataset ID from updated resource.');
    }

    const createDatasetVersionOperation =
      await this.createDatasetVersionResourceInternal({
        datasetName: datasetId,
        displayName:
          config?.versionDisplayName || `prompt_version_${Date.now()}`,
        config,
      });

    const datasetVersionResourceName = await this._waitForOperation(
      createDatasetVersionOperation,
      config?.timeout ?? Prompts._DEFAULT_TIMEOUT,
      (config?.maxWaitTime ?? Prompts._DEFAULT_MAX_WAIT_TIME) * 1000,
    );

    const versionId = datasetVersionResourceName.split('/').pop();
    if (!versionId) {
      throw new Error('Failed to parse version ID created during update.');
    }

    const datasetVersionResource = await this.getDatasetVersionResourceInternal(
      {
        datasetId,
        datasetVersionId: versionId,
      },
    );

    const updatedPrompt = this._createPromptFromDatasetMetadata(
      datasetVersionResource,
    );
    (updatedPrompt as any)._dataset = updatedDatasetResource;
    (updatedPrompt as any)._dataset_version = datasetVersionResource;

    return updatedPrompt;
  }

  private async createDatasetResourceInternal(
    params: types.CreateDatasetParameters,
  ): Promise<types.DatasetOperation> {
    let response: Promise<types.DatasetOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.createDatasetParametersToVertex(params);
      path = common.formatMap(
        'datasets',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetOperation>;

      return response.then((resp) => {
        return resp as types.DatasetOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async createDatasetVersionResourceInternal(
    params: types.CreateDatasetVersionParameters,
  ): Promise<types.DatasetOperation> {
    let response: Promise<types.DatasetOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.createDatasetVersionParametersToVertex(params);
      path = common.formatMap(
        'datasets/{name}/datasetVersions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetOperation>;

      return response.then((resp) => {
        return resp as types.DatasetOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getDatasetResourceInternal(
    params: types.GetDatasetParameters,
  ): Promise<types.Dataset> {
    let response: Promise<types.Dataset>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getDatasetParametersToVertex(params);
      path = common.formatMap(
        'datasets/{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Dataset>;

      return response.then((resp) => {
        return resp as types.Dataset;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getDatasetVersionResourceInternal(
    params: types.GetDatasetVersionParameters,
  ): Promise<types.DatasetVersion> {
    let response: Promise<types.DatasetVersion>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getDatasetVersionParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions/{dataset_version_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetVersion>;

      return response.then((resp) => {
        return resp as types.DatasetVersion;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getDatasetOperationInternal(
    params: types.GetDatasetOperationParameters,
  ): Promise<types.DatasetOperation> {
    let response: Promise<types.DatasetOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getDatasetOperationParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/operations/{operation_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DatasetOperation>;

      return response.then((resp) => {
        return resp as types.DatasetOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async listPromptsInternal(
    params: types.ListDatasetsRequestParameters,
  ): Promise<types.ListDatasetsResponse> {
    let response: Promise<types.ListDatasetsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.listDatasetsRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListDatasetsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListDatasetsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async listVersionsInternal(
    params: types.ListDatasetVersionsRequestParameters,
  ): Promise<types.ListDatasetVersionsResponse> {
    let response: Promise<types.ListDatasetVersionsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listDatasetVersionsRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListDatasetVersionsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListDatasetVersionsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async deleteDatasetInternal(
    params: types.DeleteDatasetRequestParameters,
  ): Promise<types.DeletePromptOperation> {
    let response: Promise<types.DeletePromptOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.deleteDatasetRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeletePromptOperation>;

      return response.then((resp) => {
        return resp as types.DeletePromptOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async deleteDatasetVersionInternal(
    params: types.DeletePromptVersionRequestParameters,
  ): Promise<types.DeletePromptVersionOperation> {
    let response: Promise<types.DeletePromptVersionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deletePromptVersionRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions/{version_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeletePromptVersionOperation>;

      return response.then((resp) => {
        return resp as types.DeletePromptVersionOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async restoreVersionInternal(
    params: types.RestoreVersionRequestParameters,
  ): Promise<types.RestoreVersionOperation> {
    let response: Promise<types.RestoreVersionOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.restoreVersionRequestParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}/datasetVersions/{version_id}:restore',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.RestoreVersionOperation>;

      return response.then((resp) => {
        return resp as types.RestoreVersionOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async updateDatasetResourceInternal(
    params: types.UpdateDatasetParameters,
  ): Promise<types.Dataset> {
    let response: Promise<types.Dataset>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.updateDatasetParametersToVertex(params);
      path = common.formatMap(
        'datasets/{dataset_id}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'PATCH',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Dataset>;

      return response.then((resp) => {
        return resp as types.Dataset;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
