/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_sandboxsnapshots_converters.js';
import * as types from './types.js';

export class SandboxSnapshots extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  async createInternal(
    params: types.CreateSandboxEnvironmentSnapshotRequestParameters,
  ): Promise<types.AgentEngineSandboxSnapshotOperation> {
    let response: Promise<types.AgentEngineSandboxSnapshotOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createSandboxEnvironmentSnapshotRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}:snapshot',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSandboxSnapshotOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSandboxSnapshotOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async deleteInternal(
    params: types.DeleteSandboxEnvironmentSnapshotRequestParameters,
  ): Promise<types.DeleteSandboxEnvironmentSnapshotOperation> {
    let response: Promise<types.DeleteSandboxEnvironmentSnapshotOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteSandboxEnvironmentSnapshotRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteSandboxEnvironmentSnapshotOperation>;

      return response.then((resp) => {
        return resp as types.DeleteSandboxEnvironmentSnapshotOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getInternal(
    params: types.GetSandboxEnvironmentSnapshotRequestParameters,
  ): Promise<types.SandboxEnvironmentSnapshot> {
    let response: Promise<types.SandboxEnvironmentSnapshot>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getSandboxEnvironmentSnapshotRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SandboxEnvironmentSnapshot>;

      return response.then((resp) => {
        return resp as types.SandboxEnvironmentSnapshot;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListSandboxEnvironmentSnapshotsRequestParameters,
  ): Promise<types.ListSandboxEnvironmentSnapshotsResponse> {
    let response: Promise<types.ListSandboxEnvironmentSnapshotsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listSandboxEnvironmentSnapshotsRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/sandboxEnvironmentSnapshots',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListSandboxEnvironmentSnapshotsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListSandboxEnvironmentSnapshotsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getSandboxSnapshotOperation(
    params: types.GetAgentEngineSandboxSnapshotOperationParameters,
  ): Promise<types.AgentEngineSandboxSnapshotOperation> {
    let response: Promise<types.AgentEngineSandboxSnapshotOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSandboxSnapshotOperationParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSandboxSnapshotOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSandboxSnapshotOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
