/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_sandboxtemplates_converters.js';
import * as types from './types.js';

export class SandboxTemplates extends BaseModule {
  constructor(
    private readonly apiClient: ApiClient,
    private readonly ensureDefaultParent?: () => Promise<string>,
  ) {
    super();
  }

  /**
   * Resolves the parent agent engine name, falling back to a shared default
   * agent engine when the caller does not provide one.
   */
  private async resolveParentName(name?: string): Promise<string> {
    if (name) {
      return name;
    }
    if (!this.ensureDefaultParent) {
      throw new Error('An agent engine name is required.');
    }
    return this.ensureDefaultParent();
  }

  /**
   * Creates a sandbox environment template and returns the operation. If `name`
   * (the parent agent engine) is omitted, a shared default agent engine is used.
   */
  async create(
    params: Omit<
      types.CreateSandboxEnvironmentTemplateRequestParameters,
      'name'
    > & {
      name?: string;
    },
  ): Promise<types.SandboxEnvironmentTemplateOperation> {
    const name = await this.resolveParentName(params.name);
    return this.createInternal({...params, name});
  }

  /** Returns the sandbox environment template with the specified name. */
  async get(
    params: types.GetSandboxEnvironmentTemplateRequestParameters,
  ): Promise<types.SandboxEnvironmentTemplate> {
    return this.getInternal(params);
  }

  /**
   * Lists the sandbox environment templates. If `name` (the parent agent
   * engine) is omitted, a shared default agent engine is used.
   */
  async list(
    params: Omit<
      types.ListSandboxEnvironmentTemplatesRequestParameters,
      'name'
    > & {
      name?: string;
    } = {},
  ): Promise<types.ListSandboxEnvironmentTemplatesResponse> {
    const name = await this.resolveParentName(params.name);
    return this.listInternal({...params, name});
  }

  /** Deletes the sandbox environment template and returns the operation. */
  async delete(
    params: types.DeleteSandboxEnvironmentTemplateRequestParameters,
  ): Promise<types.DeleteSandboxEnvironmentTemplateOperation> {
    return this.deleteInternal(params);
  }

  async createInternal(
    params: types.CreateSandboxEnvironmentTemplateRequestParameters,
  ): Promise<types.SandboxEnvironmentTemplateOperation> {
    let response: Promise<types.SandboxEnvironmentTemplateOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createSandboxEnvironmentTemplateRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/sandboxEnvironmentTemplates',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SandboxEnvironmentTemplateOperation>;

      return response.then((resp) => {
        return resp as types.SandboxEnvironmentTemplateOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async deleteInternal(
    params: types.DeleteSandboxEnvironmentTemplateRequestParameters,
  ): Promise<types.DeleteSandboxEnvironmentTemplateOperation> {
    let response: Promise<types.DeleteSandboxEnvironmentTemplateOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteSandboxEnvironmentTemplateRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteSandboxEnvironmentTemplateOperation>;

      return response.then((resp) => {
        return resp as types.DeleteSandboxEnvironmentTemplateOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getInternal(
    params: types.GetSandboxEnvironmentTemplateRequestParameters,
  ): Promise<types.SandboxEnvironmentTemplate> {
    let response: Promise<types.SandboxEnvironmentTemplate>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getSandboxEnvironmentTemplateRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SandboxEnvironmentTemplate>;

      return response.then((resp) => {
        return resp as types.SandboxEnvironmentTemplate;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListSandboxEnvironmentTemplatesRequestParameters,
  ): Promise<types.ListSandboxEnvironmentTemplatesResponse> {
    let response: Promise<types.ListSandboxEnvironmentTemplatesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listSandboxEnvironmentTemplatesRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/sandboxEnvironmentTemplates',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListSandboxEnvironmentTemplatesResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListSandboxEnvironmentTemplatesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getSandboxEnvironmentTemplateOperation(
    params: types.GetSandboxEnvironmentTemplateOperationParameters,
  ): Promise<types.SandboxEnvironmentTemplateOperation> {
    let response: Promise<types.SandboxEnvironmentTemplateOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getSandboxEnvironmentTemplateOperationParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SandboxEnvironmentTemplateOperation>;

      return response.then((resp) => {
        return resp as types.SandboxEnvironmentTemplateOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
