/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_sandboxes_converters.js';
import {SandboxEnvironments} from './sandboxenvironments.js';
import {SandboxSnapshots} from './sandboxsnapshots.js';
import {SandboxTemplates} from './sandboxtemplates.js';
import * as types from './types.js';

export class Sandboxes extends BaseModule {
  public readonly environments: SandboxEnvironments;
  public readonly templates: SandboxTemplates;
  public readonly snapshots: SandboxSnapshots;

  constructor(
    private readonly apiClient: ApiClient,
    private readonly ensureDefaultParent?: () => Promise<string>,
  ) {
    super();
    this.environments = new SandboxEnvironments(apiClient, ensureDefaultParent);
    this.templates = new SandboxTemplates(apiClient, ensureDefaultParent);
    this.snapshots = new SandboxSnapshots(apiClient, ensureDefaultParent);
  }

  /**
   * Resolves the parent agent engine name, falling back to a shared default
   * agent engine when the caller does not provide one.
   */
  private async resolveParentName(name?: string): Promise<string> {
    if (name) {
      return name;
    }
    if (!this.ensureDefaultParent) {
      throw new Error('An agent engine name is required.');
    }
    return this.ensureDefaultParent();
  }

  /**
   * Creates a sandbox environment and returns the operation. If `name` (the
   * parent agent engine) is omitted, a shared default agent engine is used.
   */
  async create(
    params: Omit<types.CreateAgentEngineSandboxRequestParameters, 'name'> & {
      name?: string;
    },
  ): Promise<types.AgentEngineSandboxOperation> {
    const name = await this.resolveParentName(params.name);
    return this.createInternal({...params, name});
  }

  /** Deletes the sandbox environment and returns the operation. */
  async delete(
    params: types.DeleteAgentEngineSandboxRequestParameters,
  ): Promise<types.DeleteAgentEngineSandboxOperation> {
    return this.deleteInternal(params);
  }

  /** Executes code in the sandbox environment. */
  async executeCode(
    params: types.ExecuteCodeAgentEngineSandboxRequestParameters,
  ): Promise<types.ExecuteSandboxEnvironmentResponse> {
    return this.executeCodeInternal(params);
  }

  /** Returns the sandbox environment with the specified name. */
  async get(
    params: types.GetAgentEngineSandboxRequestParameters,
  ): Promise<types.SandboxEnvironment> {
    return this.getInternal(params);
  }

  /**
   * Lists the sandbox environments. If `name` (the parent agent engine) is
   * omitted, a shared default agent engine is used.
   */
  async list(
    params: Omit<types.ListAgentEngineSandboxesRequestParameters, 'name'> & {
      name?: string;
    } = {},
  ): Promise<types.ListAgentEngineSandboxesResponse> {
    const name = await this.resolveParentName(params.name);
    return this.listInternal({...params, name});
  }

  /** Returns the sandbox operation with the specified name. */
  async getSandboxOperation(
    params: types.GetAgentEngineSandboxOperationParameters,
  ): Promise<types.AgentEngineSandboxOperation> {
    return this.getSandboxOperationInternal(params);
  }

  async createInternal(
    params: types.CreateAgentEngineSandboxRequestParameters,
  ): Promise<types.AgentEngineSandboxOperation> {
    let response: Promise<types.AgentEngineSandboxOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createAgentEngineSandboxRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/sandboxEnvironments',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSandboxOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSandboxOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async deleteInternal(
    params: types.DeleteAgentEngineSandboxRequestParameters,
  ): Promise<types.DeleteAgentEngineSandboxOperation> {
    let response: Promise<types.DeleteAgentEngineSandboxOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteAgentEngineSandboxRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteAgentEngineSandboxOperation>;

      return response.then((resp) => {
        return resp as types.DeleteAgentEngineSandboxOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async executeCodeInternal(
    params: types.ExecuteCodeAgentEngineSandboxRequestParameters,
  ): Promise<types.ExecuteSandboxEnvironmentResponse> {
    let response: Promise<types.ExecuteSandboxEnvironmentResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.executeCodeAgentEngineSandboxRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/:execute',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ExecuteSandboxEnvironmentResponse>;

      return response.then((resp) => {
        const typedResp = new types.ExecuteSandboxEnvironmentResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getInternal(
    params: types.GetAgentEngineSandboxRequestParameters,
  ): Promise<types.SandboxEnvironment> {
    let response: Promise<types.SandboxEnvironment>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSandboxRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SandboxEnvironment>;

      return response.then((resp) => {
        return resp as types.SandboxEnvironment;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListAgentEngineSandboxesRequestParameters,
  ): Promise<types.ListAgentEngineSandboxesResponse> {
    let response: Promise<types.ListAgentEngineSandboxesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listAgentEngineSandboxesRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/sandboxEnvironments',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListAgentEngineSandboxesResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListAgentEngineSandboxesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getSandboxOperationInternal(
    params: types.GetAgentEngineSandboxOperationParameters,
  ): Promise<types.AgentEngineSandboxOperation> {
    let response: Promise<types.AgentEngineSandboxOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSandboxOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSandboxOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSandboxOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
