/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as genaiTypes from '@google/genai';
import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_sandboxes_converters.js';
import * as types from './types.js';

export class Sandboxes extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  async createInternal(
    params: types.CreateAgentEngineSandboxRequestParameters,
  ): Promise<types.AgentEngineSandboxOperation> {
    let response: Promise<types.AgentEngineSandboxOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.createAgentEngineSandboxRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/sandboxEnvironments',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSandboxOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSandboxOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async deleteInternal(
    params: types.DeleteAgentEngineSandboxRequestParameters,
  ): Promise<types.DeleteAgentEngineSandboxOperation> {
    let response: Promise<types.DeleteAgentEngineSandboxOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.deleteAgentEngineSandboxRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'DELETE',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.DeleteAgentEngineSandboxOperation>;

      return response.then((resp) => {
        return resp as types.DeleteAgentEngineSandboxOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async executeCodeInternal(
    params: types.ExecuteCodeAgentEngineSandboxRequestParameters,
  ): Promise<types.ExecuteSandboxEnvironmentResponse> {
    let response: Promise<types.ExecuteSandboxEnvironmentResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.executeCodeAgentEngineSandboxRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/:execute',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ExecuteSandboxEnvironmentResponse>;

      return response.then((resp) => {
        const typedResp = new types.ExecuteSandboxEnvironmentResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getInternal(
    params: types.GetAgentEngineSandboxRequestParameters,
  ): Promise<types.SandboxEnvironment> {
    let response: Promise<types.SandboxEnvironment>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSandboxRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SandboxEnvironment>;

      return response.then((resp) => {
        return resp as types.SandboxEnvironment;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListAgentEngineSandboxesRequestParameters,
  ): Promise<types.ListAgentEngineSandboxesResponse> {
    let response: Promise<types.ListAgentEngineSandboxesResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listAgentEngineSandboxesRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}/sandboxEnvironments',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListAgentEngineSandboxesResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListAgentEngineSandboxesResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async getSandboxOperationInternal(
    params: types.GetAgentEngineSandboxOperationParameters,
  ): Promise<types.AgentEngineSandboxOperation> {
    let response: Promise<types.AgentEngineSandboxOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.getAgentEngineSandboxOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AgentEngineSandboxOperation>;

      return response.then((resp) => {
        return resp as types.AgentEngineSandboxOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
