/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as genaiTypes from '@google/genai';
import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_sessionevents_converters.js';
import * as types from './types.js';

export class SessionEvents extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  async append(
    params: types.AppendAgentEngineSessionEventRequestParameters,
  ): Promise<types.AppendAgentEngineSessionEventResponse> {
    let response: Promise<types.AppendAgentEngineSessionEventResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.appendAgentEngineSessionEventRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}:appendEvent',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.AppendAgentEngineSessionEventResponse>;

      return response.then((resp) => {
        const typedResp = new types.AppendAgentEngineSessionEventResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  async listInternal(
    params: types.ListAgentEngineSessionEventsRequestParameters,
  ): Promise<types.ListAgentEngineSessionEventsResponse> {
    let response: Promise<types.ListAgentEngineSessionEventsResponse>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body =
        converters.listAgentEngineSessionEventsRequestParametersToVertex(
          params,
        );
      path = common.formatMap(
        '{name}/events',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.['httpOptions'] as
            | genaiTypes.HttpOptions
            | undefined,
          abortSignal: params.config?.['abortSignal'] as
            | AbortSignal
            | undefined,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.ListAgentEngineSessionEventsResponse>;

      return response.then((resp) => {
        const typedResp = new types.ListAgentEngineSessionEventsResponse();
        Object.assign(typedResp, resp);
        return typedResp;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
