/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import * as common from '@google/genai/vertex_internal';
import {ApiClient, BaseModule} from '@google/genai/vertex_internal';
import * as converters from './converters/_skills_converters.js';
import * as types from './types.js';

export class Skills extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  /**
   * Creates a new Skill.
   *
   * @param params Parameters for creating a Skill.
   * @return A Promise resolving to the created Skill if waitForCompletion is true, or the SkillOperation otherwise.
   */
  async create(
    params: types.CreateSkillRequestParameters,
  ): Promise<types.Skill | types.SkillOperation> {
    const config = params.config ? {...params.config} : {};
    const localPath = config.localPath;
    const zippedFilesystem = config.zippedFilesystem;

    if (localPath && zippedFilesystem) {
      throw new Error(
        'Only one of `localPath` or `zippedFilesystem` can be provided in config.',
      );
    }
    if (!localPath && !zippedFilesystem) {
      throw new Error(
        'Either `localPath` or `zippedFilesystem` must be provided in config.',
      );
    }

    let zippedFilesystemPayload: unknown = zippedFilesystem;

    if (localPath) {
      // Document that local path deployment is only available in Node.js environments.
      // Using dynamic imports ensures compatibility with non-Node runtime environments (e.g. browsers)
      // as long as this code path is not executed.
      let archiverModule;
      let streamModule;
      let bufferModule;
      try {
        const archiverName = 'archiver';
        archiverModule = await import(archiverName);
        streamModule = await import('stream');
        bufferModule = await import('buffer');
      } catch {
        throw new Error(
          'Zipping localPath is only supported in Node.js environments with `archiver` installed.',
        );
      }
      const archiver = archiverModule.default;
      const {Writable} = streamModule;
      const {Buffer} = bufferModule;

      const chunks: Uint8Array[] = [];
      const writable = new Writable({
        write(
          chunk: unknown,
          encoding: string,
          callback: (error?: Error | null) => void,
        ) {
          chunks.push(
            Buffer.from(chunk as Uint8Array | string) as unknown as Uint8Array,
          );
          callback();
        },
      });

      const archive = archiver('zip', {zlib: {level: 9}});
      archive.pipe(writable);
      archive.directory(localPath, false);
      await archive.finalize();

      await new Promise((resolve, reject) => {
        writable.on('finish', resolve);
        writable.on('error', reject);
        archive.on('error', reject);
      });

      zippedFilesystemPayload = Buffer.concat(chunks).toString('base64');
    } else if (zippedFilesystemPayload != null) {
      if (
        typeof zippedFilesystemPayload === 'object' &&
        zippedFilesystemPayload instanceof Uint8Array
      ) {
        const bufferModule = await import('buffer');
        const {Buffer} = bufferModule;
        zippedFilesystemPayload = Buffer.from(zippedFilesystemPayload).toString(
          'base64',
        );
      }
    }

    config.zippedFilesystem = zippedFilesystemPayload;
    const requestParams: types.CreateSkillRequestParameters = {
      ...params,
      config: config,
    };

    let operation = await this.createInternal(requestParams);

    const waitForCompletion = config.waitForCompletion ?? true;
    if (waitForCompletion) {
      while (!operation.done) {
        // Wait 2 seconds before polling again
        await new Promise((resolve) => setTimeout(resolve, 2000));
        if (!operation.name) {
          throw new Error('Operation name is missing.');
        }
        operation = await this.getSkillOperationInternal({
          operationName: operation.name,
          config: {
            httpOptions: config.httpOptions,
            abortSignal: config.abortSignal,
          },
        });
      }

      if (operation.error) {
        throw new Error(
          `Failed to create Skill: ${JSON.stringify(operation.error)}`,
        );
      }

      if (!operation.response?.name) {
        throw new Error(
          'Operation completed successfully but did not return a Skill resource name.',
        );
      }

      return await this.get({
        name: operation.response.name,
        config: {
          httpOptions: config.httpOptions,
          abortSignal: config.abortSignal,
        },
      });
    }

    return operation;
  }

  async get(params: types.GetSkillRequestParameters): Promise<types.Skill> {
    let response: Promise<types.Skill>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getSkillRequestParametersToVertex(params);
      path = common.formatMap(
        '{name}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.Skill>;

      return response.then((resp) => {
        return resp as types.Skill;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async createInternal(
    params: types.CreateSkillRequestParameters,
  ): Promise<types.SkillOperation> {
    let response: Promise<types.SkillOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.createSkillRequestParametersToVertex(params);
      path = common.formatMap(
        'skills',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'POST',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SkillOperation>;

      return response.then((resp) => {
        return resp as types.SkillOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }

  private async getSkillOperationInternal(
    params: types.GetSkillOperationParameters,
  ): Promise<types.SkillOperation> {
    let response: Promise<types.SkillOperation>;

    let path: string = '';
    let queryParams: Record<string, string> = {};
    if (this.apiClient.isVertexAI()) {
      const body = converters.getSkillOperationParametersToVertex(params);
      path = common.formatMap(
        '{operationName}',
        body['_url'] as Record<string, unknown>,
      );
      queryParams = body['_query'] as Record<string, string>;
      delete body['_url'];
      delete body['_query'];
      delete body['config'];

      response = this.apiClient
        .request({
          path: path,
          queryParams: queryParams,
          body: JSON.stringify(body),
          httpMethod: 'GET',
          httpOptions: params.config?.httpOptions,
          abortSignal: params.config?.abortSignal,
        })
        .then((httpResponse) => {
          return httpResponse.json();
        }) as Promise<types.SkillOperation>;

      return response.then((resp) => {
        return resp as types.SkillOperation;
      });
    } else {
      throw new Error(
        'This method is only supported by the Gemini Enterprise Agent Platform (previously known as Vertex AI).',
      );
    }
  }
}
