name: Add Label to PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
    - name: Add kokoro force run label to the PR
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "kokoro:force-run"
